force-app/main/default/objects/Affiliate_Account__c/Affiliate_Account__c.object-meta.xml
<CustomObject>
    <label>Affiliate Account</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Affiliate Account No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliate Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Account__c/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <label>Affiliate</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliate Users</relationshipLabel>
    <relationshipName>Affiliate_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Affiliate_Account__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Affiliate_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <description>The affiliate to which the contact is most closely connected.</description>
    <inlineHelpText>Select the affiliate to which the contact is most closely connected.  Go to www.toolbank.org/citycodes to view a city code list.</inlineHelpText>
    <label>Affiliate</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ATL</fullName>
            </value>
            <value>
                <fullName>BLT</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>CIN</fullName>
            </value>
            <value>
                <fullName>CLT</fullName>
            </value>
            <value>
                <fullName>DEN</fullName>
            </value>
            <value>
                <fullName>DET</fullName>
            </value>
            <value>
                <fullName>HFD</fullName>
            </value>
            <value>
                <fullName>HOU</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NWK</fullName>
            </value>
            <value>
                <fullName>PDX</fullName>
            </value>
            <value>
                <fullName>PHX</fullName>
            </value>
            <value>
                <fullName>RVA</fullName>
            </value>
            <value>
                <fullName>SAT</fullName>
            </value>
            <value>
                <fullName>SAV</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
                <default>true</default>
                <label>USA</label>
            </value>
            <value>
                <fullName>WDC</fullName>
            </value>
            <value>
                <fullName>WNS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EnableContactAsCommunityUser.cls
public without Sharing class EnableContactAsCommunityUser {
    
    @AuraEnabled
    public static String createCommuinityUser(String recordId){
        Profile pf = [Select id,name from Profile where name ='TB Members Plus' limit 1];
        Contact con = [select id,name,email,lastname,firstname,accountid from contact where Id=:recordId limit 1];
        String Rnd = '';
        User usr = new User();
        usr.contactId=con.Id;
        usr.username=con.Email+'.TB';
        usr.firstname=con.FirstName;
        usr.lastname=con.LastName;
        usr.email=con.Email;
        usr.communityNickname = con.LastName+'_'+con.FirstName+'_TB';
        usr.alias = string.valueof(con.FirstName.substring(0,1) + con.LastName.substring(0,1));
        usr.profileid = pf.Id;
        usr.emailencodingkey='UTF-8';
        usr.languagelocalekey='en_US';
        usr.localesidkey='en_US';
        usr.timezonesidkey='America/Los_Angeles';
        Database.DMLOptions dlo = new Database.DMLOptions();
        dlo.EmailHeader.triggerUserEmail= true;
        Database.saveresult sr = Database.insert(usr,dlo);

        
        //system.Site.createExternalUser(usr,con.accountid,'4444444',true);
        if (!sr.isSuccess()) {
            for(Database.Error err: sr.getErrors()){
                throw new AuraHandledException(err.getMessage());
            }
        }else{
            insert new Affiliate_Account__c(Affiliate__c = con.accountid, user__c = usr.Id);
            setPassword(usr.Id);
        }

        return 'Success';
    }

    @future
    public static void setPassword(String userId){

        system.resetPassword(userId,true);
        User usr = [SELECT Id,username, ContactId FROM USER WHERE Id=:userId];
        contact con = new contact(id=usr.ContactId,username__c =usr.username);

        update con;
    }

}