force-app/main/default/objects/Order/fields/Actual_Pickup_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Pickup_Date_Time__c</fullName>
    <label>Actual Pickup Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order/fields/Amount_Owed__c.field-meta.xml
<CustomField>
    <fullName>Amount_Owed__c</fullName>
    <formula>Total_Amount__c - Amount_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Owed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <label>Amount Paid</label>
    <summarizedField>Payments_TB__c.Amount__c</summarizedField>
    <summaryForeignKey>Payments_TB__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dataloader__c.field-meta.xml
<CustomField>
    <fullName>Dataloader__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dataloader</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Actual_Pickup_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Pickup_Date_Time__c</fullName>
    <formula>Order.Actual_Pickup_Date_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Pickup Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Check_In_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Check In Quantity</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Check_Out_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Quantity__c</fullName>
    <label>Check Out Quantity</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Damaged__c.field-meta.xml
<CustomField>
    <fullName>Damaged__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Damaged</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Inventory_Tool__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Tool__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Order Tool</relationshipLabel>
    <relationshipName>Order_Tools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Lost__c.field-meta.xml
<CustomField>
    <fullName>Lost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lost</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unconfirmed</fullName>
                <default>true</default>
                <label>Unconfirmed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Partially Returned</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>OverDue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
                <isActive>false</isActive>
                <label>Damaged</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Partially confirmed</fullName>
                <isActive>false</isActive>
                <label>Partially confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_Fees__c.field-meta.xml
<CustomField>
    <fullName>Total_Fees__c</fullName>
    <formula>Lost_Fee__c + Late_Fee__c + Total_Handling_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payments_TB__c/Payments_TB__c.object-meta.xml
<CustomObject>
    <label>Payment by Member</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payments_TB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments by Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payments_TB__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payments_TB__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments by Members</relationshipLabel>
    <relationshipName>Payments_by_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tool</fullName>
            </value>
            <value>
                <fullName>Additional Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Txn-{00000000}</displayFormat>
        <label>Transaction No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Worn - Out</fullName>
            </value>
            <value>
                <fullName>No Longer Carry</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Gift Card</fullName>
            </value>
            <value>
                <fullName>Restricted Funds</fullName>
            </value>
            <value>
                <fullName>General Funds</fullName>
            </value>
            <value>
                <fullName>Corporate Donation</fullName>
            </value>
            <value>
                <fullName>Individual Donation</fullName>
            </value>
            <value>
                <fullName>Member Agency Donation</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Rebranding</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Destroyed</fullName>
            </value>
            <value>
                <fullName>Increase</fullName>
            </value>
            <value>
                <fullName>Decrease</fullName>
            </value>
            <value>
                <fullName>Lost - Return</fullName>
            </value>
            <value>
                <fullName>Lost from Inventory</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
                <isActive>false</isActive>
                <label>Allocated</label>
            </value>
            <value>
                <fullName>Donated</fullName>
                <isActive>false</isActive>
                <label>Donated</label>
            </value>
            <value>
                <fullName>Donation</fullName>
                <isActive>false</isActive>
                <label>Donation</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Purchased</fullName>
                <isActive>false</isActive>
                <label>Purchased</label>
            </value>
            <value>
                <fullName>Return</fullName>
                <isActive>false</isActive>
                <label>Return</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/Damaged.recordType-meta.xml
<RecordType>
    <fullName>Damaged</fullName>
    <active>false</active>
    <label>Damaged</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Fulfilled.recordType-meta.xml
<RecordType>
    <fullName>Fulfilled</fullName>
    <active>true</active>
    <label>Fulfilled</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Lost.recordType-meta.xml
<RecordType>
    <fullName>Lost</fullName>
    <active>true</active>
    <label>Lost</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Returned.recordType-meta.xml
<RecordType>
    <fullName>Returned</fullName>
    <active>true</active>
    <label>Returned</label>
</RecordType>

force-app/main/default/objects/Trigger_Validation__c/Trigger_Validation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Validation</label>
</CustomObject>

force-app/main/default/classes/OrderItemHelperClass.cls
public class OrderItemHelperClass {
    public static Boolean recursion = false;
    static final String LOST = Schema.SObjectType.Transaction__c.getRecordTypeInfosByDeveloperName().get('Lost').getRecordTypeId();
    static final String RE_TURN =Schema.SObjectType.Transaction__c.getRecordTypeInfosByDeveloperName().get('Returned').getRecordTypeId();
    static final String OUT = Schema.SObjectType.Transaction__c.getRecordTypeInfosByDeveloperName().get('Fulfilled').getRecordTypeId();

    public static void createTransactionOnInsert(List<OrderItem> itemList){
        List<Transaction__c> transactionList = new List<Transaction__c>();
        for(OrderItem tool: itemList){
            String newStatus = tool.status__c;
            Boolean isFullfilled = 'Fulfilled'.equalsIgnoreCase(newStatus);
            Boolean isReturned = 'Returned'.equalsIgnoreCase(newStatus);
            Boolean isDamaged = 'Damaged'.equalsIgnoreCase(newStatus);
            Boolean isLost = 'Lost'.equalsIgnoreCase(newStatus);
            Boolean isPartiallyReturned = 'Partially Returned'.equalsIgnoreCase(newStatus);
            if(isFullfilled || isReturned || isDamaged || isLost || isPartiallyReturned){
                if(tool.Check_In_Quantity__c != null && tool.Check_In_Quantity__c != 0){
                    Transaction__c trans = returnTrans(tool, RE_TURN,null,tool.Check_In_Quantity__c);
                    transactionList.add(trans);
                }
                
                if(tool.Lost__c != null && tool.Lost__c != 0){
                    Transaction__c trans = returnTrans(tool, LOST,'Lost - Return',tool.Lost__c);
                    transactionList.add(trans);
                }
                
                if(tool.Damaged__c != null && tool.Damaged__c != 0){
                    Transaction__c trans = returnTrans(tool, RE_TURN,'Damaged',tool.Damaged__c);
                    transactionList.add(trans);
                }
                
                if(tool.Check_Out_Quantity__c != null && tool.Check_Out_Quantity__c != 0){
                    Transaction__c trans = returnTrans(tool, OUT,null,tool.Check_Out_Quantity__c);
                    transactionList.add(trans);
                }
            }
        }

        if(!transactionList.isEmpty()){
            insert transactionList;
        }
    }
    public static void createTransaction(List<OrderItem> itemList, Map<Id, OrderItem> oldMap){

        List<Transaction__c> transactionList = new List<Transaction__c>();
        for(OrderItem item: itemList){
            OrderItem oldItem = oldMap.get(item.Id);
            String oldStatus, newStatus;
            newStatus = item.status__c;
            oldStatus = oldItem.status__c;  
            Boolean isCheckInSame = (item.Check_In_Quantity__c == oldItem.Check_In_Quantity__c);
            Boolean isCheckOutSame = (item.Check_Out_Quantity__c ==  oldItem.Check_Out_Quantity__c);
            Boolean isLostSame = (item.Lost__c == oldItem.Lost__c);
            Boolean isDamangeSame = (item.Damaged__c == oldItem.Damaged__c);
            Boolean isFullfilled = 'Fulfilled'.equalsIgnoreCase(newStatus);
            Boolean isReturned = 'Returned'.equalsIgnoreCase(newStatus);
            Boolean isDamaged = 'Damaged'.equalsIgnoreCase(newStatus);
            Boolean isLost = 'Lost'.equalsIgnoreCase(newStatus);
            Boolean isPartiallyReturned = 'Partially Returned'.equalsIgnoreCase(newStatus);
            Decimal checkInNew = item.Check_In_Quantity__c != Null?item.Check_In_Quantity__c:0;
            Decimal checkInOld = oldItem.Check_In_Quantity__c != Null?oldItem.Check_In_Quantity__c:0;
            Decimal lostNew = item.Lost__c != Null?item.Lost__c:0;
            Decimal lostOld = oldItem.Lost__c != Null?oldItem.Lost__c:0;
            Decimal damagedNew = item.Damaged__c != Null?item.Damaged__c:0;
            Decimal damagedOld = oldItem.Damaged__c != Null?oldItem.Damaged__c:0;
            Decimal checkOutNew = item.Check_Out_Quantity__c != Null?item.Check_Out_Quantity__c:0;
            Decimal checkOutOld = oldItem.Check_Out_Quantity__c != Null?oldItem.Check_Out_Quantity__c:0;
           system.debug('isCheckOutSame :: '+ isCheckOutSame);
            if(!isCheckOutSame ){ //&& isFullfilled
                Decimal diff = checkOutNew - checkOutOld;
                system.debug('diff :: '+ diff);
                if(diff != 0){
                    Transaction__c trans = returnTrans(item,OUT,null,diff);
                    transactionList.add(trans);
                }
            }
            
            if((!isCheckInSame || !isLostSame || !isDamangeSame) ){ //&& (isReturned || isPartiallyReturned || isDamaged || isLost)

                Decimal diff = checkInNew - checkInOld;
                if(diff != 0){
                    Transaction__c trans = returnTrans(item, RE_TURN,null,diff);
                    transactionList.add(trans);
                }

                Decimal diffLost = lostNew - lostOld;
                if(diffLost != 0){
                    Transaction__c trans = returnTrans(item, LOST,'Lost - Return',diffLost);
                    transactionList.add(trans);
                }

                Decimal diffDamaged = damagedNew - damagedOld;
                if(diffDamaged != 0){
                    Transaction__c trans = returnTrans(item, RE_TURN,'Damaged',diffDamaged);
                    transactionList.add(trans);
                } 

            }


        }

        if(!transactionList.isEmpty()){
            insert transactionList;
        }
    }

    static Transaction__c returnTrans(OrderItem item, String recordTypeId, String subType, Decimal quantity){
        Transaction__c trans = new Transaction__c();
        trans.Inventory__c = item.Inventory_Tool__c;
        trans.Order_Product__c = item.Id;
        trans.recordTypeId = recordTypeId;
        trans.sub_type__c = subType;
        trans.quantity__c = quantity;

        return trans;
    }


    public static void handleStatus(List<OrderItem> itemList){
        recursion = true;
        set<Id> orderIdSet = new set<Id>();
        for(orderitem item: itemList){
            orderIdSet.add(item.orderid);
        }

        List<Order> orderListToUpdate = new List<Order>();
        for(Order order:    [SELECT Id,Amount_Owed__c,Amount_Paid__c,Status,
                            (SELECT Id,Total_Fees__c,isDeleted,TotalPrice,Status__c,Product2.Type__c FROM OrderItems WHERE isDeleted = false ),
                            (SELECT Id,Amount__c FROM Payments_by_Members__r)
                            FROM Order WHERE Id IN: orderIdSet AND dataloader__c = false]) //WHERE Product2.Type__c = 'Tool'
        {
            Boolean unconfirmed=false,confirmed=false,partiallyReturned=false,fulfilled=false,cancelled=false,overdue=false,returned=false,closed=false,unpaid=false;
            Boolean isUpdate = false;
            String orderStatus = order.status;
            Decimal totalAmount = 0.0;
            for(OrderItem item: order.OrderItems){
                if(item.Product2.Type__c == 'Tool'){
                        totalAmount += item.Total_Fees__c;
                    if('Unconfirmed'.equalsIgnoreCase(item.Status__c) || 'Unavailable'.equalsIgnoreCase(item.Status__c))
                        unconfirmed = true;
                    if('confirmed'.equalsIgnoreCase(item.Status__c))
                        confirmed = true;
                    if('fulfilled'.equalsIgnoreCase(item.Status__c))
                        fulfilled = true;
                    if('cancelled'.equalsIgnoreCase(item.Status__c))
                        cancelled = true;
                    if('overdue'.equalsIgnoreCase(item.Status__c))
                        overdue = true;
                    if('returned'.equalsIgnoreCase(item.Status__c))
                        returned = true;
                    if('closed'.equalsIgnoreCase(item.Status__c))
                        closed = true;
                    if('unpaid'.equalsIgnoreCase(item.Status__c))
                        unpaid = true;
                    if('Partially Returned'.equalsIgnoreCase(item.Status__c))
                        partiallyReturned = true;
                }else{
                    totalAmount +=item.TotalPrice;
                }
            }
            Decimal amountPaid = 0.00;
            for(Payments_TB__c payment: order.Payments_by_Members__r){
                amountPaid += payment.Amount__c;
            }

            Decimal owedAmount = totalAmount - amountPaid;

            if(unconfirmed && !confirmed && !fulfilled){
                order.status = 'Unconfirmed';
                isUpdate = true;
            }else if(unconfirmed && confirmed){
                order.status = 'Partially Confirmed';
                isUpdate = true;
            }else if(!unconfirmed && confirmed ){
                order.status = 'Confirmed';
                isUpdate = true;
            }else if(unconfirmed && fulfilled ){
                order.status = 'Fulfilled';
                isUpdate = true;
            }else if(!unconfirmed && !confirmed && fulfilled && !cancelled && !overdue && !returned && !partiallyReturned ){
                if( orderStatus != 'Fulfilled'){
                    order.status = 'Fulfilled';
                    order.Actual_Pickup_Date_Time__c = system.now();
                    isUpdate = true;
                }
            }else if(!unconfirmed && !confirmed && !fulfilled && cancelled && !overdue && !returned && !partiallyReturned ){
                order.status = 'Cancelled';
                isUpdate = true;
            }else if( overdue){
                order.status = 'Overdue';
                isUpdate = true;
            }else if(!unconfirmed && !confirmed && !fulfilled && !cancelled && !overdue && returned && !partiallyReturned ){
                order.status = 'Returned';
                if(owedAmount > 0){
                    order.status = 'Unpaid';
                }else if(owedAmount == 0){
                    order.status = 'Closed';
                }
                isUpdate = true;
            }else if(partiallyReturned){
                order.status = 'Partially Returned';
                isUpdate = true;
            }else if(fulfilled && (returned || partiallyReturned )){
                order.status = 'Partially Returned';
                isUpdate = true;
            }else{
                if(owedAmount >= 0){
                    order.status = 'Unpaid';
                    isUpdate = true;
                }
                
            }
            if(isUpdate)
                orderListToUpdate.add(order);
        }

        if(!orderListToUpdate.isEmpty()){
            ByPassValidations.ordStatusValidation = true;
            update orderListToUpdate;
        }
    }


    public static void quantityAndPriceValidation(List<OrderItem> itemList, Map<Id, OrderItem> oldMap){

        for(OrderItem item: itemList){
            Decimal newQty = item.quantity;
            Decimal oldQty = oldMap.get(item.Id).quantity;
            Decimal newPrice = item.UnitPrice;
            Decimal oldPrice = oldMap.get(item.Id).UnitPrice;
            String currentUserProfileId = Userinfo.getProfileId();
            Trigger_Validation__c mc = Trigger_Validation__c.getInstance(currentUserProfileId);
            Boolean isNotAllowed = (mc == null || (mc != null && !mc.Active__c));
            if(newQty != oldQty && !ByPassValidations.ordItemPriceAndQtyValidation && isNotAllowed){
                item.addError(' Insufficient Permissions.');
            }else if(newPrice != oldPrice && !ByPassValidations.ordItemPriceAndQtyValidation && isNotAllowed){
                item.addError(' Insufficient Permissions.');
            }
        }
    }
}