force-app/main/default/objects/Order/fields/Amount_Owed__c.field-meta.xml
<CustomField>
    <fullName>Amount_Owed__c</fullName>
    <formula>Total_Amount__c - Amount_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Owed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Available_Credits__c.field-meta.xml
<CustomField>
    <fullName>Available_Credits__c</fullName>
    <formula>Account.Available_Credits_R__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Credits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payments_TB__c/Payments_TB__c.object-meta.xml
<CustomObject>
    <label>Payment by Member</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payments_TB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments by Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payments_TB__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payments_TB__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payments_TB__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments by Members</relationshipLabel>
    <relationshipName>Payments_by_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payments_TB__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Payment_Method.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Credit Card</fullName>
        <default>true</default>
        <label>Credit Card</label>
    </customValue>
    <customValue>
        <fullName>Check</fullName>
    </customValue>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Online Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Organizational Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Waiver - Disaster Related Event</fullName>
    </customValue>
    <customValue>
        <fullName>Waiver - External Sponsor</fullName>
    </customValue>
    <customValue>
        <fullName>Waiver - Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Waiver - Internal Promotion</fullName>
    </customValue>
    <masterLabel>Payment Method</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreatePaymentController.cls
public without sharing class CreatePaymentController {
    
    @AuraEnabled(cacheable=true)
    public static order getOrderDetails(String recordId){

        return [SELECT Id,Name,Amount_Owed__c,Available_Credits__c,OrderNumber FROM Order WHERE Id=: recordId];
    }

    @AuraEnabled
    public static String createPayment(String payment){

        Map<String,object> paymentObj = (Map<String,object>)JSON.deserializeUntyped(payment);
        Payments_TB__c pay = new Payments_TB__c();
        pay.Order__c = (String)paymentObj.get('orderId');
        pay.Comment__c = (String)paymentObj.get('comments');
        pay.Amount__c = String.isNotBlank((String)paymentObj.get('amount'))? Double.valueOf((String)paymentObj.get('amount')):0;
        pay.Payment_Method__c = (String)paymentObj.get('method');
        insert pay;
        return 'Success';
    }
}