force-app/main/default/objects/Order/fields/Lost_R_Fee__c.field-meta.xml
<CustomField>
    <fullName>Lost_R_Fee__c</fullName>
    <label>Lost Fee</label>
    <summarizedField>OrderItem.Lost_Fee__c</summarizedField>
    <summaryFilterItems>
        <field>OrderItem.Lost__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Total_Handling_Fees__c.field-meta.xml
<CustomField>
    <fullName>Total_Handling_Fees__c</fullName>
    <label>Total Handling Fees</label>
    <summarizedField>OrderItem.Total_Handling_Fee__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Total_Late_Fee__c.field-meta.xml
<CustomField>
    <fullName>Total_Late_Fee__c</fullName>
    <label>Total Late Fee</label>
    <summarizedField>OrderItem.Late_Fee__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payments_TB__c/Payments_TB__c.object-meta.xml
<CustomObject>
    <label>Payment by Member</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payments_TB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments by Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payments_TB__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payments_TB__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments by Members</relationshipLabel>
    <relationshipName>Payments_by_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payments_TB__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Toolbank_Help_Page__mdt/Toolbank_Help_Page__mdt.object-meta.xml
<CustomObject>
    <label>Toolbank Help Page</label>
    <pluralLabel>Toolbank Help Page</pluralLabel>
</CustomObject>

force-app/main/default/globalValueSets/Payment_Method.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Credit Card</fullName>
        <default>true</default>
        <label>Credit Card</label>
    </customValue>
    <customValue>
        <fullName>Check</fullName>
    </customValue>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Online Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Organizational Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Waiver - Disaster Related Event</fullName>
    </customValue>
    <customValue>
        <fullName>Waiver - External Sponsor</fullName>
    </customValue>
    <customValue>
        <fullName>Waiver - Forgiven</fullName>
    </customValue>
    <customValue>
        <fullName>Waiver - Internal Promotion</fullName>
    </customValue>
    <masterLabel>Payment Method</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PaymentReceipt_Ctrl.cls
public class PaymentReceipt_Ctrl {
    public List<Toolbank_Help_Page__mdt> getData {get;set;}
    public Decimal waiver {get;set;}
    public Decimal orgCredit {get;set;}
    public Decimal creditCard {get;set;}
    public Decimal totalpaid {get;set;}
    public Decimal totalOrderFees {get;set;}
    String orderId;
    public Double offset{get{
        TimeZone tz = UserInfo.getTimeZone();
        //Milliseconds to Day
        return  tz.getOffset(DateTime.now()) / (1000 * 3600 * 24.00);
    }}

    public PaymentReceipt_Ctrl(Apexpages.StandardController sc){
        totalOrderFees = 0.00;
        getData= Toolbank_Help_Page__mdt.getAll().values();
        orderId = sc.getId();
        Order order = (Order)sc.getRecord();
        waiver = 0.00;
        orgCredit = 0.00;
        creditCard = 0.00;
        totalpaid = 0.00;
        totalOrderFees += order.Total_Handling_Fees__c != null?order.Total_Handling_Fees__c:0;
        totalOrderFees += order.Total_Late_Fee__c != null?order.Total_Late_Fee__c:0;
        totalOrderFees += order.Lost_R_Fee__c != null?order.Lost_R_Fee__c:0;
        totalOrderFees = totalOrderFees.setScale(2);
        for(Payments_TB__c payment: [SELECT Id, Payment_Method__c, Amount__c FROM Payments_TB__c WHERE Order__c =: orderId ]){
            if(payment.Payment_Method__c == 'Credit Card'){
                creditCard += payment.Amount__c;
            }else if(payment.Payment_Method__c == 'Organizational Credit'){
                orgCredit += payment.Amount__c;
            }else if(payment.Payment_Method__c == 'Waiver - External Sponsor' || payment.Payment_Method__c == 'Waiver - External Sponsor'){
                waiver += payment.Amount__c;
            }
            totalpaid += payment.Amount__c;
        }
    }

    public void updateOrder(){
       
            PageReference PDf =  Page.PaymentReceipt;//Replace attachmentPDf with the page you have rendered as PDF
            PDf.getParameters().put('Id',orderId);
            PDf.setRedirect(true);
            Attachment attach = new Attachment();
            Blob b ;
            b = PDf.getContentAsPDF();
            attach.Body = b;
            attach.Name = 'Payment_Receipt_'+Date.today().format()+'.pdf';
            attach.IsPrivate = false;
            attach.ParentId = orderId;
            insert attach;
        
    }
}