force-app/main/default/objects/Asset/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <formula>Account.Affiliate_Handling_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Affiliate Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Current_Inventory_F__c.field-meta.xml
<CustomField>
    <fullName>Current_Inventory_F__c</fullName>
    <formula>Quantity -( Damaged_F__c  +  Maintenance_F__c + Other_R__c +  Rebranding_F__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field includes On Shelf and Out but not including Rebranding/Maintenance, Damaged, Other.</inlineHelpText>
    <label>Current Inventory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/On_Shelf_Quantity_F__c.field-meta.xml
<CustomField>
    <fullName>On_Shelf_Quantity_F__c</fullName>
    <formula>Current_Inventory_F__c - Out_F__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>These tools are currently in the warehouse but may be reserved for other orders.</inlineHelpText>
    <label>On Shelf Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliate</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliate Orders</relationshipLabel>
    <relationshipName>AffiliateOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Requested_Borrowing_Period__c.field-meta.xml
<CustomField>
    <fullName>Requested_Borrowing_Period__c</fullName>
    <label>Requested Borrowing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 week</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
            </value>
            <value>
                <fullName>3 weeks</fullName>
            </value>
            <value>
                <fullName>4 weeks</fullName>
            </value>
            <value>
                <fullName>5 weeks</fullName>
            </value>
            <value>
                <fullName>6 weeks</fullName>
            </value>
            <value>
                <fullName>7 weeks</fullName>
            </value>
            <value>
                <fullName>8 weeks</fullName>
            </value>
            <value>
                <fullName>9 weeks</fullName>
            </value>
            <value>
                <fullName>10 weeks</fullName>
            </value>
            <value>
                <fullName>11 weeks</fullName>
            </value>
            <value>
                <fullName>12 weeks</fullName>
            </value>
            <value>
                <fullName>13 weeks</fullName>
            </value>
            <value>
                <fullName>14 weeks</fullName>
            </value>
            <value>
                <fullName>15 weeks</fullName>
            </value>
            <value>
                <fullName>16 weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Schedule_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Return_Date__c</fullName>
    <label>Schedule Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <label>Affiliate Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Inventory_Tool__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Tool__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Order Tool</relationshipLabel>
    <relationshipName>Order_Tools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Lowest_Available_Quantity_For_this_Item__c.field-meta.xml
<CustomField>
    <fullName>Lowest_Available_Quantity_For_this_Item__c</fullName>
    <description>Test Field will be removed later if needed</description>
    <label>Lowest Available Quantity For this Item</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Requested_Borrowing_Period__c.field-meta.xml
<CustomField>
    <fullName>Requested_Borrowing_Period__c</fullName>
    <label>Requested Borrowing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 week</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
            </value>
            <value>
                <fullName>3 weeks</fullName>
            </value>
            <value>
                <fullName>4 weeks</fullName>
            </value>
            <value>
                <fullName>5 weeks</fullName>
            </value>
            <value>
                <fullName>6 weeks</fullName>
            </value>
            <value>
                <fullName>7 weeks</fullName>
            </value>
            <value>
                <fullName>8 weeks</fullName>
            </value>
            <value>
                <fullName>9 weeks</fullName>
            </value>
            <value>
                <fullName>10 weeks</fullName>
            </value>
            <value>
                <fullName>11 weeks</fullName>
            </value>
            <value>
                <fullName>12 weeks</fullName>
            </value>
            <value>
                <fullName>13 weeks</fullName>
            </value>
            <value>
                <fullName>14 weeks</fullName>
            </value>
            <value>
                <fullName>15 weeks</fullName>
            </value>
            <value>
                <fullName>16 weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Reserved_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Reserved_Quantity__c</fullName>
    <label>Confirmed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Schedule_Pick_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Pick_Date__c</fullName>
    <label>Schedule Pick Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Schedule_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Return_Date__c</fullName>
    <label>Schedule Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unconfirmed</fullName>
                <default>true</default>
                <label>Unconfirmed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Partially Returned</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>OverDue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
                <isActive>false</isActive>
                <label>Damaged</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Partially confirmed</fullName>
                <isActive>false</isActive>
                <label>Partially confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tool_Handling_Fee_Per_Item__c.field-meta.xml
<CustomField>
    <fullName>Tool_Handling_Fee_Per_Item__c</fullName>
    <formula>Affiliate_Handling_Fee__c * UnitPrice*1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tool Handling Fee Per Item</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Total_Handling_Fee__c</fullName>
    <formula>Affiliate_Handling_Fee__c * UnitPrice * Quantity *if(ISPICKVAL(Requested_Borrowing_Period__c , &quot;1 week&quot;),  VALUE( TRIM(SUBSTITUTE(TEXT(Requested_Borrowing_Period__c) , &quot;week&quot;, &quot;&quot;))), VALUE(TRIM(SUBSTITUTE(TEXT(Requested_Borrowing_Period__c) , &quot;weeks&quot;, &quot;&quot;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tool_Note__c.field-meta.xml
<CustomField>
    <fullName>Tool_Note__c</fullName>
    <label>Tool Note</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tool</fullName>
            </value>
            <value>
                <fullName>Additional Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LowestQuantityCalculateClasss.cls
public class LowestQuantityCalculateClasss {

public static void lowestQuantityOrder2(List<Order> orderList){
    List<OrderItem> newOrderItemList = lowestQuantityOrder3( orderList);
    update newOrderItemList;


}
    
    public static  List<OrderItem> lowestQuantityOrder3(List<Order> orderList){
        List<Date> dateList = new List<Date>();
        Map<Id, Order> orderMap = new Map<Id, Order>(orderList);
        List<OrderItem> newOrderItemList = [SELECT product2.Name,
                                            Id,
                                            Quantity,
                                            Order.Affiliate__c,
                                            Reserved_Quantity__c,
                                            Affiliate_Handling_Fee__c,
                                            Inventory_Tool__r.Current_Inventory_F__c,
                                            Inventory_Tool__r.On_Shelf_Quantity_F__c,
                                            product2Id,
                                            PriceBookEntryId,
                                            Inventory_Tool__c,
                                            Product2.productCode,
                                            product2.Tool_Note__c,
                                            Requested_Borrowing_Period__c,
                                            Tool_Handling_Fee_Per_Item__c,
                                            Status__c,
                                            UnitPrice,
                                            Total_Handling_Fee__c,
                                            LastModifiedDate,
                                            Schedule_Pick_Date__c,
                                            Schedule_Return_Date__c 
                                            FROM OrderItem 
                                            WHERE OrderId IN:orderList
                                            AND Product2.type__c = 'Tool' 
                                            AND Status__c != 'Returned'
                                            ORDER BY product2.Name ASC];
        if(newOrderItemList != null && newOrderItemList.size()>0){
            Set<Id> productIdSet = new set<Id>();

            for(OrderItem item: newOrderItemList){
                productIdSet.add(item.product2Id);
            //  for(Date d=item.Schedule_Pick_Date__c; d<=item.Schedule_Return_Date__c;d.addDays(1)){
                    
                    dateList.add(item.Schedule_Pick_Date__c);
                    dateList.add(item.Schedule_Return_Date__c);
                //}
            }

            dateList.sort();
            Date minPickDate = dateList[0];
            Date maxReturnDate = dateList[dateList.size()-1];
            system.debug('dateList :: '+ dateList);
            List<OrderItem> oldItemList =   [SELECT Id,product2Id,
                                            PriceBookEntryId,
                                            Order.Affiliate__c,
                                            Inventory_Tool__c,
                                            Affiliate_Handling_Fee__c,
                                            LastModifiedDate,Quantity,
                                            Lowest_Available_Quantity_For_this_Item__c,
                                            Reserved_Quantity__c,
                                            Schedule_Pick_Date__c,
                                            Schedule_Return_Date__c 
                                            FROM OrderItem 
                                            WHERE Product2.Type__c = 'Tool'
                                            AND Status__c != 'Returned'
                                            AND Status__c != 'Cancelled'
                                            AND Order.Affiliate__c =: orderList[0].Affiliate__c
                                            AND product2Id IN: productIdSet 
                                            AND Id NOT IN: newOrderItemList
                                            AND Schedule_Pick_Date__c <=: maxReturnDate
                                            AND Schedule_Return_Date__c >=: minPickDate
                                            ORDER BY LastModifiedDate ASC];
            
            Map<Id,Map<id, List<OrderItem>>> affiliateToproductIdToItemListMap = new Map<Id,Map<Id, List<OrderItem>>>();

            for(OrderItem item: oldItemList){
                if(!affiliateToproductIdToItemListMap.containsKey(item.Order.Affiliate__c))
                    affiliateToproductIdToItemListMap.put(item.Order.Affiliate__c, new Map<id, List<OrderItem>>());

                Map<id, List<OrderItem>> productIdToItemListMap = affiliateToproductIdToItemListMap.get(item.Order.Affiliate__c);

                if(!productIdToItemListMap.containsKey(item.product2Id))
                    productIdToItemListMap.put(item.product2Id, new List<OrderItem>());

                productIdToItemListMap.get(item.product2Id).add(item);
            }

            for(OrderItem item: newOrderItemList){
                system.debug(item);
                system.debug(item.Order.Affiliate__c);
                //system.debug(affiliateToproductIdToItemListMap.get(item.Order.Affiliate__c).get(item.product2Id));
                List<OrderItem> itemList = affiliateToproductIdToItemListMap.containsKey(item.Order.Affiliate__c)?affiliateToproductIdToItemListMap.get(item.Order.Affiliate__c).get(item.product2Id):null;
                Decimal lowest = lowestQuantityItemDate(item,itemList);
                item.Lowest_Available_Quantity_For_this_Item__c = lowest<0?0:lowest;
                lowest = lowest>item.quantity?item.quantity:lowest;
                if(item.Reserved_Quantity__c == Null)
                    item.Reserved_Quantity__c = lowest<0?0:lowest;
            }
                
            return newOrderItemList;
        } else return null;

    }

    @AuraEnabled
    public static Decimal singleItemLowestQuantity(String itemId, String product2Id, Date pickupDate, Date returnDate,String affilliateId){

        system.debug('itemId '+itemId +' product2Id '+product2Id+' pickupDate '+pickupDate+' returnDate '+returnDate);
        List<OrderItem> allItemList =   [SELECT Id,product2Id,
                                        LastModifiedDate,Quantity,
                                        PriceBookEntryId,
                                        Inventory_Tool__c,
                                        Affiliate_Handling_Fee__c,
                                        Inventory_Tool__r.Current_Inventory_F__c,
                                        Lowest_Available_Quantity_For_this_Item__c,
                                        Reserved_Quantity__c,
                                        Schedule_Pick_Date__c,
                                        Schedule_Return_Date__c 
                                        FROM OrderItem 
                                        WHERE ((product2Id =: product2Id 
                                        AND Schedule_Pick_Date__c <=: returnDate
                                        AND Schedule_Return_Date__c >=: pickupDate)
                                        OR Id =: itemId)
                                        AND Product2.Type__c = 'Tool'
                                        AND Order.Affiliate__c =:affilliateId
                                        ORDER BY LastModifiedDate ASC];
        Map<Id, OrderItem> itemMap = new Map<Id, OrderItem>(allItemList);

        orderItem orderItem = itemMap.remove(itemId);orderItem.Schedule_Pick_Date__c = pickupDate;orderItem.Schedule_Return_Date__c = returnDate;

        return lowestQuantityItemDate(orderItem, DateTime.now(), itemMap.values());
    }
    
    
    
    public static Decimal lowestQuantityItemDate(orderItem orderItem, List<orderItem> existingOrderItems){

        
        List<Decimal> qtyList = new List<Decimal>();
        
            for(Date dt=orderItem.Schedule_Pick_Date__c;dt<=orderItem.Schedule_Return_Date__c;dt = dt.addDays(1)){
                Decimal reservedQuantity =0;
                Decimal currentInventory = orderItem.Inventory_Tool__r.Current_Inventory_F__c!= null?orderItem.Inventory_Tool__r.Current_Inventory_F__c:0;
                if(existingOrderItems != Null){
                    for(OrderItem item: existingOrderItems){

                        if(dt <= item.Schedule_Return_Date__c && dt >= item.Schedule_Pick_Date__c ) 
                        {
                                reservedQuantity += item.Reserved_Quantity__c!= Null?item.Reserved_Quantity__c:0;   
                                
                        }
                    }
            }

            currentInventory = currentInventory -reservedQuantity;
            qtyList.add(currentInventory);
            
        }

        qtyList.sort();

        Decimal lowestAvailableQuantity = (qtyList != Null && qtyList.size() >0)?qtyList[0]:0;

        return lowestAvailableQuantity;

    }

    public static Decimal lowestQuantityItemDate(orderItem orderItem, DateTime lastmodified, List<orderItem> existingOrderItems){

       
       
        Decimal lowestAvailableQuantity = lowestQuantityItemDate(orderItem,existingOrderItems);

        return lowestAvailableQuantity <0 ?0:lowestAvailableQuantity;

    }
    public Decimal lowestQuantityItem(orderItem orderItem, List<orderItem> existingOrderItems){

        Decimal reservedQuantity = 0;
        for(OrderItem item: existingOrderItems){

            if(item.LastModifiedDate <= OrderItem.LastModifiedDate ) { reservedQuantity += item.quantity;}
        }

        Decimal lowestAvailableQuantity = orderItem.Inventory_Tool__r.Current_Inventory_F__c - reservedQuantity;

        return lowestAvailableQuantity;

    }


}