force-app/main/default/objects/Asset/fields/Total_Stock_Historical__c.field-meta.xml
<CustomField>
    <fullName>Total_Stock_Historical__c</fullName>
    <inlineHelpText>This field denotes the number of tools added to the inventory over a period of time. It will only be incremented.</inlineHelpText>
    <label>Total Stock (Historical)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Txn-{00000000}</displayFormat>
        <label>Transaction No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Worn - Out</fullName>
            </value>
            <value>
                <fullName>No Longer Carry</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Gift Card</fullName>
            </value>
            <value>
                <fullName>Restricted Funds</fullName>
            </value>
            <value>
                <fullName>General Funds</fullName>
            </value>
            <value>
                <fullName>Corporate Donation</fullName>
            </value>
            <value>
                <fullName>Individual Donation</fullName>
            </value>
            <value>
                <fullName>Member Agency Donation</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Rebranding</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Destroyed</fullName>
            </value>
            <value>
                <fullName>Increase</fullName>
            </value>
            <value>
                <fullName>Decrease</fullName>
            </value>
            <value>
                <fullName>Lost - Return</fullName>
            </value>
            <value>
                <fullName>Lost from Inventory</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
                <isActive>false</isActive>
                <label>Allocated</label>
            </value>
            <value>
                <fullName>Donated</fullName>
                <isActive>false</isActive>
                <label>Donated</label>
            </value>
            <value>
                <fullName>Donation</fullName>
                <isActive>false</isActive>
                <label>Donation</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Purchased</fullName>
                <isActive>false</isActive>
                <label>Purchased</label>
            </value>
            <value>
                <fullName>Return</fullName>
                <isActive>false</isActive>
                <label>Return</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/Back_In_Service.recordType-meta.xml
<RecordType>
    <fullName>Back_In_Service</fullName>
    <active>true</active>
    <label>Back In Service</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Damaged.recordType-meta.xml
<RecordType>
    <fullName>Damaged</fullName>
    <active>false</active>
    <label>Damaged</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <label>Donation</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Lost.recordType-meta.xml
<RecordType>
    <fullName>Lost</fullName>
    <active>true</active>
    <label>Lost</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Out_Of_Service.recordType-meta.xml
<RecordType>
    <fullName>Out_Of_Service</fullName>
    <active>true</active>
    <label>Out Of Service</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Purchased.recordType-meta.xml
<RecordType>
    <fullName>Purchased</fullName>
    <active>true</active>
    <label>Purchased</label>
</RecordType>

force-app/main/default/classes/TransactionTriggerHandler.cls
public with sharing class TransactionTriggerHandler {

    static final String  DONATION='012020000000L9zAAE', DAMAGED='012020000000L9QAAU',BACK_IN_SERVICE='012020000000LJzAAM',
            INTERNAL_AUDIT='012020000000L9fAAE',LOST='012020000000L9kAAE',PURCHASED='012020000000L9RAAU',
            RETIRE='012020000000L9aAAE',RE_TURN='012020000000L9uAAE',OUT='012020000000LJuAAM',OUT_OF_SERVICE='012020000000LJVAA2';
            
    public static void updqteQuantity(List<Transaction__c> transList){

        for (Transaction__c tran : transList) {
            String RecordTypeId = tran.RecordTypeId;
            String subType = tran.sub_type__c;
            if(BACK_IN_SERVICE.equals(RecordTypeId)){ // Back in service
                tran.quantity__c = (-tran.quantity__c);
            }
        }
    }
    
    public static void transaction(List<Transaction__c> transList) {
        
        Map<Id, List<Transaction__c>> InvIdToTranMap = new Map<Id, List<Transaction__c>>();
        for(Transaction__c tran: transList){

            if(tran.inventory__c != null){
                if(!InvIdToTranMap.containsKey(tran.inventory__c))
                    InvIdToTranMap.put(tran.inventory__c, new List<Transaction__c>());
                
                    InvIdToTranMap.get(tran.inventory__c).add(tran);
            }
        }
       
        
        List<Asset> assestListToUpdate = new List<Asset>();
        for(Asset asset: [SELECT Id,Total_Stock_Historical__c,quantity FROM Asset WHERE ID IN: InvIdToTranMap.keyset()]){
            
            Decimal his=0,total=0,curr=0,shelf=0;
            

            for(Transaction__c tran: InvIdToTranMap.get(asset.Id)){
                Decimal quantity = tran.quantity__c;
                quantity = quantity <0?(-quantity):quantity;

              /*  if(oldmap != Null && oldmap.containsKey(tran.id)){
                    Decimal oldQuantity = oldmap.get(tran.id).quantity__c;
                    oldQuantity = oldQuantity <0?(-oldQuantity):oldQuantity;
                    quantity = quantity - oldQuantity;
                }*/
                system.System.debug('quantity :: '+quantity + 'his :: '+his + 'total :: '+total );
                String RecordTypeId = tran.RecordTypeId;
                if(DONATION.equals(RecordTypeId)){ // Donation
                    his += quantity;
                    total += quantity;
                }else if(PURCHASED.equals(RecordTypeId)){ // purchased
                    his += quantity;
                    total += quantity;
                }else if(LOST.equals(RecordTypeId)){ // Lost
                    total -= quantity;
                    
                }else if(RETIRE.equals(RecordTypeId)){ // Retire
                    total -= quantity;
                }else if(INTERNAL_AUDIT.equals(RecordTypeId)){ // Inventory Audit
                    
                    if('Increase'.equals(tran.sub_type__c)){
                        total += quantity;
                    }else if('Decrease'.equals(tran.sub_type__c)){
                        total += quantity;
                    }
                    
                }
            }
            
            asset.quantity = (asset.quantity != null?asset.quantity:0) +total;
            asset.Total_Stock_Historical__c = (asset.Total_Stock_Historical__c != null?asset.Total_Stock_Historical__c:0) +his;
            
           
            assestListToUpdate.add(asset);

        }

        if(!assestListToUpdate.isEmpty())
            update assestListToUpdate;

    }
}