force-app/main/default/objects/Account/recordTypes/Affiliate.recordType-meta.xml
<RecordType>
    <fullName>Affiliate</fullName>
    <active>true</active>
    <description>Affiliate Account</description>
    <label>Affiliate</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Member_Agency.recordType-meta.xml
<RecordType>
    <fullName>Member_Agency</fullName>
    <active>true</active>
    <description>ToolBank Member Agency</description>
    <label>Member Agency</label>
</RecordType>

force-app/main/default/objects/Affiliate_Account__c/Affiliate_Account__c.object-meta.xml
<CustomObject>
    <label>Affiliate Account</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Affiliate Account No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliate Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Account__c/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <label>Affiliate</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliate Users</relationshipLabel>
    <relationshipName>Affiliate_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Affiliate_Account__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Affiliate_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <description>The affiliate to which the contact is most closely connected.</description>
    <inlineHelpText>Select the affiliate to which the contact is most closely connected.  Go to www.toolbank.org/citycodes to view a city code list.</inlineHelpText>
    <label>Affiliate</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ATL</fullName>
            </value>
            <value>
                <fullName>BLT</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>CIN</fullName>
            </value>
            <value>
                <fullName>CLT</fullName>
            </value>
            <value>
                <fullName>DEN</fullName>
            </value>
            <value>
                <fullName>DET</fullName>
            </value>
            <value>
                <fullName>HFD</fullName>
            </value>
            <value>
                <fullName>HOU</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NWK</fullName>
            </value>
            <value>
                <fullName>PDX</fullName>
            </value>
            <value>
                <fullName>PHX</fullName>
            </value>
            <value>
                <fullName>RVA</fullName>
            </value>
            <value>
                <fullName>SAT</fullName>
            </value>
            <value>
                <fullName>SAV</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
                <default>true</default>
                <label>USA</label>
            </value>
            <value>
                <fullName>WDC</fullName>
            </value>
            <value>
                <fullName>WNS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account marked as Primary in this Contact&apos;s list of Organization Affiliations.</description>
    <inlineHelpText>The Account marked as Primary in this Contact&apos;s list of Organization Affiliations.</inlineHelpText>
    <label>Primary Affiliation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Do Not Use.  Use Organization Affiliations.</relationshipLabel>
    <relationshipName>PrimaryAffiliatedContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliate</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliate Orders</relationshipLabel>
    <relationshipName>AffiliateOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SearchComponentController.cls
public without sharing class SearchComponentController {
    @AuraEnabled
    public static List<sObject> search(String objectName, List<String> fields, String searchTerm){
        String searchKeyword = searchTerm + '*';
        String returningQuery = '';
        returningQuery = objectName+' ( Id, '+String.join(fields,',')+')';
        String query = 'FIND :searchKeyword IN ALL FIELDS RETURNING '+returningQuery+' LIMIT 20';
        List<List<sObject>> searchRecords = new List<List<sObject>>();
        List<SObject> sobjList = new List<SObject>();
        if(String.isBlank(searchTerm)){
            String soqlQuery = 'SELECT '+ String.join(fields,',')+', Id, LastViewedDate FROM '+objectName+' ORDER BY LastViewedDate DESC LIMIT 5';
            system.debug(soqlQuery);
            sobjList = Database.query( soqlQuery );
            searchRecords.add(sobjList);
        }else{
            searchRecords = Search.Query(Query);
        }

        system.debug(searchRecords.get(0));
        return searchRecords.get(0);
    }

    @AuraEnabled
    public static sObject getRecentlyCreatedRecord(String recordId, List<String> fields, String objectName){
        sObject createdRecord;
        try {
            String query = 'SELECT Id, '+String.join(fields,',')+' FROM '+objectName+' WHERE Id = \''+recordId+'\'';
            List<SObject> sobjList = Database.query( query );
            createdRecord = sobjList.get(0);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return createdRecord;
    }

    @AuraEnabled
    public static List<sObject> search2(String objectName, List<String> fields, String searchTerm, String parentId){
        String searchKeyword = '%'+ searchTerm + '%';
        String query = 'SELECT Id, '+String.join(fields,',')+' FROM '+objectName+' WHERE Name like \''+searchKeyword+'\'';
        if(String.isNotBlank(parentId) && 'Contact'.equalsIgnoreCase(objectName))
            query =  query + ' AND ( AccountId = \''+parentId+'\' OR npsp__Primary_Affiliation__c = \''+parentId+'\' )';

        String agency = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Member_Agency').getRecordTypeId();
        if('Account'.equalsIgnoreCase(objectName))
            query =  query + ' AND RecordTypeId = \''+agency+'\' AND parentId= \''+parentId+'\'';

        List<SObject> sobjList = Database.query( query );
        return sobjList;
    }


    @AuraEnabled
    public static List<sObject> search3(String objectName, List<String> fields, String searchTerm, String parentId){

        List<SObject> sobjList = new List<SObject>();
        User currentUser = [SELECT Id,Name,profile.name,contactId,contact.AccountId,contact.npsp__Primary_Affiliation__c FROM User WHERE Id=: UserInfo.getUserId()];
        String searchKeyword = '%'+ searchTerm + '%';
        String query = 'SELECT Id, ';
        if('TB Members Plus'.equalsIgnoreCase(currentUser.profile.Name) || 'TB Members'.equalsIgnoreCase(currentUser.profile.Name)){

            List<Id> accIdList = new List<Id>();
            for(npe5__Affiliation__c affCon: [SELECT Id,npe5__Organization__c FROM npe5__Affiliation__c WHERE npe5__Contact__c =: currentUser.contactId AND npe5__Status__c = 'Current' ]){
                accIdList.add(affCon.npe5__Organization__c);
            } 

            if('Account'.equalsIgnoreCase(objectName)){
                query += String.join(fields,',')+' FROM '+objectName+' WHERE Name like \''+searchKeyword+'\'';
                String agency = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Member_Agency').getRecordTypeId();
                query =  query + ' AND RecordTypeId = \''+agency+ '\' AND Id IN: accIdList';

                sobjList = Database.query( query );
            }

            if(String.isNotBlank(parentId) && 'Contact'.equalsIgnoreCase(objectName)){
                query += 'npe5__Contact__r.Name,npe5__Contact__r.Email FROM npe5__Affiliation__c WHERE npe5__Contact__r.Name like \''+searchKeyword+'\'';
                query += ' AND npe5__Status__c = \'Current\' AND npe5__Organization__c = \''+parentId+'\'';
        
                for(npe5__Affiliation__c affCon: (List<npe5__Affiliation__c>)Database.query( query )){

                    sobjList.add(affCon.npe5__Contact__r);
                }
            }



        }else{

            if('Account'.equalsIgnoreCase(objectName)){
                query += String.join(fields,',')+' FROM '+objectName+' WHERE Name like \''+searchKeyword+'\'';
                String agency = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Member_Agency').getRecordTypeId();
                query =  query + ' AND RecordTypeId = \''+agency+'\' AND parentId= \''+parentId+'\''; 

                sobjList = Database.query( query );
            }

            if(String.isNotBlank(parentId) && 'Contact'.equalsIgnoreCase(objectName)){

                query += 'npe5__Contact__r.Name,npe5__Contact__r.Email FROM npe5__Affiliation__c WHERE npe5__Contact__r.Name like \''+searchKeyword+'\'';
                query += ' AND npe5__Status__c = \'Current\' AND npe5__Organization__c = \''+parentId+'\'';

                for(npe5__Affiliation__c affCon: (List<npe5__Affiliation__c>)Database.query( query )){

                    sobjList.add(affCon.npe5__Contact__r);
                }
            }

        }

//        List<SObject> sobjList = Database.query( query );
        return sobjList;
    }

    @AuraEnabled
    public static List<sObject> search4(String searchTerm, String currentAffiliate){
        searchTerm = '%'+searchTerm+'%';
        list<Account> accList = new List<Account>();
        for(Affiliate_Account__c afa : [SELECT Id,Affiliate__r.id,Affiliate__r.Name FROM Affiliate_Account__c WHERE Affiliate__r.Name like: searchTerm AND Affiliate__r.RecordType.Name='Affiliate' AND Affiliate__c !=: currentAffiliate AND User__c =: UserInfo.getUserId()]){
            accList.add(afa.Affiliate__r);
        }
        // if(accList.size() == 0){
        //     return [SELECT Id, Name FROM Account WHERE Name like: searchTerm AND RecordType.Name='Affiliate' AND Id !=: currentAffiliate];
        // }
        return accList;
    }

}