force-app/main/default/objects/Account/recordTypes/Affiliate.recordType-meta.xml
<RecordType>
    <fullName>Affiliate</fullName>
    <active>true</active>
    <description>Affiliate Account</description>
    <label>Affiliate</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Total_Stock_Historical__c.field-meta.xml
<CustomField>
    <fullName>Total_Stock_Historical__c</fullName>
    <inlineHelpText>This field denotes the number of tools added to the inventory over a period of time. It will only be incremented.</inlineHelpText>
    <label>Total Stock (Historical)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit__c/Credit__c.object-meta.xml
<CustomObject>
    <label>Credit</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payments_TB__c/Payments_TB__c.object-meta.xml
<CustomObject>
    <label>Payment by Member</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payments_TB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments by Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentMemberTriggerTest.cls
@isTest
public class PaymentMemberTriggerTest {
    
    @isTest
    static void unitTest_1(){
        String recordTypeid  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Member Agency').getRecordTypeId();
        Account acc = TestDataFactory.createAccount('test',recordTypeid);
        String recordTypeid2  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Affiliate').getRecordTypeId();
        
        contact con = TestDataFactory.createContact(acc.Id);
        Product2 tool = TestDataFactory.createProduct('Tool');
        Product2 addCharges = TestDataFactory.createProduct('Additional Charges');
        PricebookEntry toolpbe = TestDataFactory.createPricebookEntry(tool.Id);
        PricebookEntry pbeAdd = TestDataFactory.createPricebookEntry(addCharges.Id);
        Account Affiliate = TestDataFactory.createAccount('test2',recordTypeid2);
        Credit__c credit1 =  TestDataFactory.createCredit(acc.Id,Null);
        Asset asset = [Select Id FROM Asset];
        asset.Total_Stock_Historical__c =  10;
        asset.Quantity = 10;
        update asset;
        Order ord = TestDataFactory.createOrder(acc.Id,con.Id,Affiliate.Id);
        orderItem ordItem = TestDataFactory.createOrderItem(ord.Id,toolpbe.Id,asset.id);
        Payments_TB__c payment = TestDataFactory.createpayment(ord);

        delete payment;
    }
}