force-app/main/default/objects/Account/recordTypes/Affiliate.recordType-meta.xml
<RecordType>
    <fullName>Affiliate</fullName>
    <active>true</active>
    <description>Affiliate Account</description>
    <label>Affiliate</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Total_Stock_Historical__c.field-meta.xml
<CustomField>
    <fullName>Total_Stock_Historical__c</fullName>
    <inlineHelpText>This field denotes the number of tools added to the inventory over a period of time. It will only be incremented.</inlineHelpText>
    <label>Total Stock (Historical)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Txn-{00000000}</displayFormat>
        <label>Transaction No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/recordTypes/Back_In_Service.recordType-meta.xml
<RecordType>
    <fullName>Back_In_Service</fullName>
    <active>true</active>
    <label>Back In Service</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <label>Donation</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Inventory_Audit.recordType-meta.xml
<RecordType>
    <fullName>Inventory_Audit</fullName>
    <active>true</active>
    <label>Inventory Audit</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Lost.recordType-meta.xml
<RecordType>
    <fullName>Lost</fullName>
    <active>true</active>
    <label>Lost</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Purchased.recordType-meta.xml
<RecordType>
    <fullName>Purchased</fullName>
    <active>true</active>
    <label>Purchased</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Retired.recordType-meta.xml
<RecordType>
    <fullName>Retired</fullName>
    <active>true</active>
    <label>Retired</label>
</RecordType>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code__c/fields/zip_Code__c.field-meta.xml
<CustomField>
    <fullName>zip_Code__c</fullName>
    <externalId>true</externalId>
    <label>zip Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TransactionTriggerHandlerTest.cls
@isTest
public class TransactionTriggerHandlerTest {
    @isTest
    private static void testTransaction() {
        String recordTypeid  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Member Agency').getRecordTypeId();
        String recordTypeid2  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Affiliate').getRecordTypeId();
        
        Id DONATION = Schema.SObjectType.Transaction__c.getRecordTypeInfosByDeveloperName().get('Donation').getRecordTypeId(); 
        Id INTERNAL_AUDIT = Schema.SObjectType.Transaction__c.getRecordTypeInfosByDeveloperName().get('Inventory_Audit').getRecordTypeId();
        Id LOST = Schema.SObjectType.Transaction__c.getRecordTypeInfosByDeveloperName().get('Lost').getRecordTypeId();
        Id PURCHASED = Schema.SObjectType.Transaction__c.getRecordTypeInfosByDeveloperName().get('Purchased').getRecordTypeId();
        Id BACK_IN_SERVICE = Schema.SObjectType.Transaction__c.getRecordTypeInfosByDeveloperName().get('Back_In_Service').getRecordTypeId();
        Id RETIRE = Schema.SObjectType.Transaction__c.getRecordTypeInfosByDeveloperName().get('Retired').getRecordTypeId();
        
        Account acc = TestDataFactory.createAccount('test',recordTypeid);
        Account affiliate = TestDataFactory.createAccount('test2',recordTypeid2);
        contact con = TestDataFactory.createContact(acc.Id);
        Zip_Code__c zipCode = TestDataFactory.createZipCode('14522');
        
        acc.parentId = affiliate.Id;
        update acc;
        
        Product2 tool = TestDataFactory.createProduct('Tool');
        PricebookEntry toolpbe = TestDataFactory.createPricebookEntry(tool.Id);
                
        List<Asset> asset = [Select Id FROM Asset limit 10];
        for(Asset asst: asset){
            asst.Total_Stock_Historical__c =  10;
            asst.Quantity = 10;
        }
        update asset;
        
        Order ord = TestDataFactory.createOrder(acc.Id,con.Id,affiliate.id);
        orderItem ordItem = TestDataFactory.createOrderItem(ord.Id,toolpbe.Id,asset[0].id);
        
        Transaction__c tran = TestDataFactory.createTransaction(asset[0].id, BACK_IN_SERVICE, 'Other');
        Transaction__c tran2 = TestDataFactory.createTransaction(asset[0].id, INTERNAL_AUDIT, 'Increase');
        Transaction__c tran2A = TestDataFactory.createTransaction(asset[0].id, INTERNAL_AUDIT, 'Decrease');
        Transaction__c tran3 = TestDataFactory.createTransaction(asset[0].id, DONATION, 'Corporate Donation');
        Transaction__c tran4 = TestDataFactory.createTransaction(asset[0].id, LOST, '');
        Transaction__c tran5 = TestDataFactory.createTransaction(asset[0].id, PURCHASED, 'Gift Card');
        Transaction__c tran6 = TestDataFactory.createTransaction(asset[0].id, RETIRE, 'Sold');
    }
}