force-app/main/default/objects/Account/recordTypes/Affiliate.recordType-meta.xml
<RecordType>
    <fullName>Affiliate</fullName>
    <active>true</active>
    <description>Affiliate Account</description>
    <label>Affiliate</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Total_Stock_Historical__c.field-meta.xml
<CustomField>
    <fullName>Total_Stock_Historical__c</fullName>
    <inlineHelpText>This field denotes the number of tools added to the inventory over a period of time. It will only be incremented.</inlineHelpText>
    <label>Total Stock (Historical)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(User__c ==null , &apos;User Not Created&apos; , IF(User__c !=null &amp;&amp; User__r.IsActive, &apos;Active&apos;, &apos;Inactive&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Check_In_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Check In Quantity</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Check_Out_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Quantity__c</fullName>
    <label>Check Out Quantity</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Damaged__c.field-meta.xml
<CustomField>
    <fullName>Damaged__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Damaged</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Lost__c.field-meta.xml
<CustomField>
    <fullName>Lost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lost</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unconfirmed</fullName>
                <default>true</default>
                <label>Unconfirmed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Partially Returned</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>OverDue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
                <isActive>false</isActive>
                <label>Damaged</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Partially confirmed</fullName>
                <isActive>false</isActive>
                <label>Partially confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderItemTriggerTest.cls
@isTest
public class OrderItemTriggerTest {
 
    @isTest
    static void unitTest_1(){
        String recordTypeid  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Member Agency').getRecordTypeId();
        Account acc = TestDataFactory.createAccount('test',recordTypeid);
        String recordTypeid2  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Affiliate').getRecordTypeId();
        
        contact con = TestDataFactory.createContact(acc.Id);
        Product2 tool = TestDataFactory.createProduct('Tool');
        Product2 addCharges = TestDataFactory.createProduct('Additional Charges');
        PricebookEntry toolpbe = TestDataFactory.createPricebookEntry(tool.Id);
        PricebookEntry pbeAdd = TestDataFactory.createPricebookEntry(addCharges.Id);
        Account Affiliate = TestDataFactory.createAccount('test2',recordTypeid2);
        Asset asset = [Select Id FROM Asset];
        asset.Total_Stock_Historical__c =  10;
        asset.Quantity = 10;
        update asset;
        Order ord = TestDataFactory.createOrder(acc.Id,con.Id,Affiliate.Id);
        orderItem ordItem = TestDataFactory.createOrderItem(ord.Id,toolpbe.Id,asset.id);
        ordItem.Check_Out_Quantity__c = 5;
        update ordItem;

        OrderItemHelperClass.recursion = false;
        ordItem.Lost__c = 1;
        ordItem.Damaged__c = 1;
        ordItem.Check_In_Quantity__c = 3;
        update ordItem;

        OrderItemHelperClass.recursion = false;
        ordItem.Status__c = 'Confirmed';
        update ordItem;

        OrderItemHelperClass.recursion = false;
        ordItem.Status__c = 'Fulfilled';
        update ordItem;

        OrderItemHelperClass.recursion = false;
        ordItem.Status__c = 'Cancelled';
        update ordItem;

        OrderItemHelperClass.recursion = false;
        ordItem.Status__c = 'Overdue';
        update ordItem;

        OrderItemHelperClass.recursion = false;
        ordItem.Status__c = 'Returned';
        update ordItem;

        OrderItemHelperClass.recursion = false;
        ordItem.Status__c = 'Closed';
        update ordItem;

        OrderItemHelperClass.recursion = false;
        ordItem.Status__c = 'Unpaid';
        update ordItem;

        OrderItemHelperClass.recursion = false;
        ordItem.Status__c = 'Partially Returned';
        update ordItem;

    }
}