force-app/main/default/objects/OrderItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Ladders</fullName>
            </value>
            <value>
                <fullName>Moving</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Special Events</fullName>
            </value>
            <value>
                <fullName>Uncategorized</fullName>
            </value>
            <value>
                <fullName>Yardwork</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Requested_Borrowing_Period__c.field-meta.xml
<CustomField>
    <fullName>Requested_Borrowing_Period__c</fullName>
    <label>Requested Borrowing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 week</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
            </value>
            <value>
                <fullName>3 weeks</fullName>
            </value>
            <value>
                <fullName>4 weeks</fullName>
            </value>
            <value>
                <fullName>5 weeks</fullName>
            </value>
            <value>
                <fullName>6 weeks</fullName>
            </value>
            <value>
                <fullName>7 weeks</fullName>
            </value>
            <value>
                <fullName>8 weeks</fullName>
            </value>
            <value>
                <fullName>9 weeks</fullName>
            </value>
            <value>
                <fullName>10 weeks</fullName>
            </value>
            <value>
                <fullName>11 weeks</fullName>
            </value>
            <value>
                <fullName>12 weeks</fullName>
            </value>
            <value>
                <fullName>13 weeks</fullName>
            </value>
            <value>
                <fullName>14 weeks</fullName>
            </value>
            <value>
                <fullName>15 weeks</fullName>
            </value>
            <value>
                <fullName>16 weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Reserved_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Reserved_Quantity__c</fullName>
    <label>Confirmed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Schedule_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Return_Date__c</fullName>
    <label>Schedule Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unconfirmed</fullName>
                <default>true</default>
                <label>Unconfirmed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Partially Returned</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>OverDue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
                <isActive>false</isActive>
                <label>Damaged</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Partially confirmed</fullName>
                <isActive>false</isActive>
                <label>Partially confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tool_Handling_Fee_Per_Item__c.field-meta.xml
<CustomField>
    <fullName>Tool_Handling_Fee_Per_Item__c</fullName>
    <formula>Affiliate_Handling_Fee__c * UnitPrice*1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tool Handling Fee Per Item</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Total_Handling_Fee__c</fullName>
    <formula>Affiliate_Handling_Fee__c * UnitPrice * Quantity *if(ISPICKVAL(Requested_Borrowing_Period__c , &quot;1 week&quot;),  VALUE( TRIM(SUBSTITUTE(TEXT(Requested_Borrowing_Period__c) , &quot;week&quot;, &quot;&quot;))), VALUE(TRIM(SUBSTITUTE(TEXT(Requested_Borrowing_Period__c) , &quot;weeks&quot;, &quot;&quot;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tool_Note__c.field-meta.xml
<CustomField>
    <fullName>Tool_Note__c</fullName>
    <label>Tool Note</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tool</fullName>
            </value>
            <value>
                <fullName>Additional Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdditionalChargesController.cls
public with sharing class AdditionalChargesController {
    
    @AuraEnabled(cacheable=true)
    public static List<PricebookEntry> getProducts(){

        return [SELECT Id,unitPrice,product2Id,Product2.Type__c,Product2.family,Product2.Name,Product2.Tool_Note__c FROM PricebookEntry WHERE Product2.Type__c ='Additional Charges' and Product2.isActive= true];
    }

    @AuraEnabled(cacheable=true)
    public static List<OrderItem> getAdditionProducts(String orderid){

        return [SELECT Id,unitPrice,OrderId,Description,product2Id,PricebookEntryId,Product2.Type__c,Product2.family,Product2.Name,Product2.Tool_Note__c FROM OrderItem WHERE OrderId=:orderid AND Product2.Type__c ='Additional Charges'];
    }

    @AuraEnabled
    public static List<OrderItem> addProducts(String orderItems){
       // try {
            system.debug(orderItems);
            list<OrderItem> orderItemList = new List<orderItem>();
            List<Object> ordItemList = (List<Object>) json.deserializeUntyped(orderItems);
            String orderid;
            for(Object obj: ordItemList){
                Map<String, object> item = (Map<String, object>)obj;
                String itemId = (string)item.get('Id');
                system.debug(item.get('OrderId'));
                if(orderid == Null)
                    orderid = (string)item.get('OrderId');
                if(String.isBlank(itemId)){
                    OrderItem orderItem = new OrderItem();
                    
                    orderItem.unitPrice =Decimal.valueOf(string.valueOf(item.get('UnitPrice')));
                    //product2id:product2id,
                    orderitem.orderid = (string)item.get('OrderId');
                   
                    orderitem.quantity = (Integer)item.get('qty');
                    orderItem.pricebookEntryId = (string)item.get('PricebookEntryId');
                    orderItem.Type__c = (string)item.get('type');
                    orderItem.category__c = (string)item.get('category');
                    orderItem.Description = (string)item.get('Description');
                    orderItemList.add(orderItem);
                }else{
                    OrderItem orderItem = new OrderItem();
                    orderItem.Id = itemId;
                    orderItem.unitPrice =Decimal.valueOf(string.valueOf(item.get('UnitPrice')));
                    orderItem.Description = (string)item.get('Description');
                    orderItemList.add(orderItem);
                }
            }
            system.debug(orderItemList);
            if(!orderItemList.isEmpty())
                upsert orderItemList;
            
            return [SELECT Id,Description,OrderId,unitPrice,product2Id,PricebookEntryId,Product2.Type__c,Product2.family,Product2.Name,Product2.Tool_Note__c FROM OrderItem WHERE OrderId=:orderid AND Product2.Type__c ='Additional Charges'];
        //} catch (Exception e) {
          //  throw new AuraHandledException(e.getMessage());
        //}

    }

    @AuraEnabled(cacheable=true)
    public static List<OrderItem> getOrderItems(string orderid){

        return [SELECT Id,OrderId,Total_Handling_Fee__c, Tool_Handling_Fee_Per_Item__c,UnitPrice,Requested_Borrowing_Period__c,Product2.Name,Schedule_Return_Date__c,Status__c,Quantity,Reserved_Quantity__c FROM OrderItem WHERE OrderId =: orderid AND Product2.Type__c ='Tool'];
    }


    @AuraEnabled
    public static List<OrderItem> deleteItems(String orderItems){
        system.debug(orderItems);
        list<OrderItem> orderItemList = new List<orderItem>();
        List<Object> ordItemList = (List<Object>) json.deserializeUntyped(orderItems);
        String orderid;
        for(Object obj: ordItemList){
            Map<String, object> item = (Map<String, object>)obj;
            String itemId = (string)item.get('Id');
            if(orderid == Null)
                orderid = (string)item.get('OrderId');
            
            system.debug(item.get('OrderId'));
            if(!String.isBlank(itemId)){
                OrderItem orderItem = new OrderItem();
                orderItem.Id = itemId;
                orderItemList.add(orderItem);
            }
        }

        if(!orderItemList.isEmpty())
            delete orderItemList;

    
        return [SELECT Id,OrderId,Description,unitPrice,product2Id,PricebookEntryId,Product2.Type__c,Product2.family,Product2.Name,Product2.Tool_Note__c FROM OrderItem WHERE OrderId=:orderid AND Product2.Type__c ='Additional Charges'];

    }
}