force-app/main/default/objects/OrderItem/fields/Schedule_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Return_Date__c</fullName>
    <label>Schedule Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unconfirmed</fullName>
                <default>true</default>
                <label>Unconfirmed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Partially Returned</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>OverDue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
                <isActive>false</isActive>
                <label>Damaged</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Partially confirmed</fullName>
                <isActive>false</isActive>
                <label>Partially confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/markOrderItemOverdue.cls
public with sharing class markOrderItemOverdue implements Database.Batchable<Sobject>, Schedulable{
 
    public Database.QueryLocator start(Database.BatchableContext BC){

        return Database.getQueryLocator([SELECT Id,Schedule_Return_Date__c FROM OrderItem WHERE (Status__c =: 'Fulfilled' OR Status__c=: 'Partially Returned' OR Status__c=: 'Overdue') ]);
    }

    public void execute(Database.BatchableContext BC, List<OrderItem> scope){
       for(orderitem item: scope){
        if(item.Schedule_Return_Date__c < Date.today())
            item.status__c = 'Overdue';
        else item.status__c = 'Fulfilled';
        
       }

       update scope;
    }

    public void finish(Database.BatchableContext BC){

    }

    public void execute(SchedulableContext sc){
        markOrderItemOverdue batch = New markOrderItemOverdue();
        database.executeBatch(batch, 200);
    }
}