force-app/main/default/objects/Account/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Affiliate Handling Fee</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <formula>Account.Affiliate_Handling_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Affiliate Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Current_Inventory_F__c.field-meta.xml
<CustomField>
    <fullName>Current_Inventory_F__c</fullName>
    <formula>Quantity -( Damaged_F__c  +  Maintenance_F__c + Other_R__c +  Rebranding_F__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field includes On Shelf and Out but not including Rebranding/Maintenance, Damaged, Other.</inlineHelpText>
    <label>Current Inventory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/On_Shelf_Quantity_F__c.field-meta.xml
<CustomField>
    <fullName>On_Shelf_Quantity_F__c</fullName>
    <formula>Current_Inventory_F__c - Out_F__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>These tools are currently in the warehouse but may be reserved for other orders.</inlineHelpText>
    <label>On Shelf Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliate</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliate Orders</relationshipLabel>
    <relationshipName>AffiliateOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Schedule_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Return_Date__c</fullName>
    <label>Schedule Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <label>Affiliate Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Inventory_Tool__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Tool__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Order Tool</relationshipLabel>
    <relationshipName>Order_Tools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Lowest_Available_Quantity_For_this_Item__c.field-meta.xml
<CustomField>
    <fullName>Lowest_Available_Quantity_For_this_Item__c</fullName>
    <description>Test Field will be removed later if needed</description>
    <label>Lowest Available Quantity For this Item</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp;OrderId,  Order.Name, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Reserved_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Reserved_Quantity__c</fullName>
    <label>Confirmed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Schedule_Pick_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Pick_Date__c</fullName>
    <label>Schedule Pick Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Schedule_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Return_Date__c</fullName>
    <label>Schedule Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unconfirmed</fullName>
                <default>true</default>
                <label>Unconfirmed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Partially Returned</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>OverDue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
                <isActive>false</isActive>
                <label>Damaged</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Partially confirmed</fullName>
                <isActive>false</isActive>
                <label>Partially confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Tool_Note__c.field-meta.xml
<CustomField>
    <fullName>Tool_Note__c</fullName>
    <label>Tool Note</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tool</fullName>
            </value>
            <value>
                <fullName>Additional Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderItemListController.cls
public without sharing class OrderItemListController {
    

    @AuraEnabled
    public static List<OrderItem> massDateChangeLowest(String orderItems){
        //try {
            
            system.debug(orderItems);
            list<object> itemList = (list<object>)JSON.deserializeUntyped(orderItems);
            system.debug(itemList);
            List<String> itemIdList = new List<String>();
            set<String> productIdSet = new set<String>();
            List<Date> dateList = new List<Date>();
            Id accountId;
            for(Object item: itemList){
                map<string, object> itemap = (map<string, object>)item;
                itemIdList.add(String.valueOf(itemap.get('id')));
                dateList.add(Date.valueOf((String)itemap.get('retDate')));
                dateList.add(Date.valueOf((String)itemap.get('pickupDate')));
                productIdSet.add((String)itemap.get('product2Id'));
                accountId = (String)itemap.get('accId');
            }
            system.debug(accountId);
            dateList.sort();
            Date minPickDate = dateList[0];
            Date maxReturnDate = dateList[dateList.size()-1];

            List<OrderItem> orderItemList =   [SELECT Id,product2Id,
                                        Product2.Tool_note__c,
                                        product2.name,
                                        LastModifiedDate,
                                        status__c,
                                        Quantity,
                                        Order.Affiliate__c,
                                        Reserved_Quantity__c,
                                        PriceBookEntryId,
                                        Affiliate_Handling_Fee__c,
                                        Inventory_Tool__c,
                                        Inventory_Tool__r.On_Shelf_Quantity_F__c,
                                        Inventory_Tool__r.Current_Inventory_F__c,
                                        Lowest_Available_Quantity_For_this_Item__c,
                                        Schedule_Pick_Date__c,
                                        Schedule_Return_Date__c 
                                        FROM OrderItem 
                                        WHERE product2Id IN: productIdSet 
                                        AND Order.Affiliate__c =: accountId
                                        AND status__c != 'Returned'
                                        AND (
                                                (Schedule_Pick_Date__c <=: maxReturnDate
                                                    AND Schedule_Return_Date__c >=: minPickDate)
                                                OR Id IN: itemIdList
                                            )
                                        ORDER BY LastModifiedDate ASC];

            Map<Id, OrderItem> orderItemMap = new Map<Id, OrderItem>(orderItemList);
            system.debug('orderItemMap :: '+orderItemMap.keySet());
            Map<id, List<OrderItem>> productIdToItemListMap =  new Map<Id, List<OrderItem>>();
            for(OrderItem item: orderItemList){
                if(!itemIdList.contains(item.id)) {
                    if(!productIdToItemListMap.containsKey(item.product2Id))
                        productIdToItemListMap.put(item.product2Id, new List<OrderItem>());
                    productIdToItemListMap.get(item.product2Id).add(item);
                }
            }
            Map<id, Asset> productIdToAssetMap =  new Map<Id, Asset>();
            for(Asset asset: [SELECT Id,Product2Id,Current_Inventory_F__c,On_Shelf_Quantity_F__c FROM Asset WHERE accountId =: accountId and Product2Id IN:productIdSet]){
                productIdToAssetMap.put(asset.Product2Id, asset);
            }
            system.debug(productIdToAssetMap);
            Map<String,Decimal> itemIdToLowest = new map<String, Decimal>();
            List<OrderItem> itemListToReturn = new List<OrderItem>();
            for(Object item: itemList){
                map<string, object> itemap = (map<string, object>)item;
               
                List<OrderItem> orderItemss = productIdToItemListMap.get((String)itemap.get('product2Id'));
                OrderItem orderItem;
                if((String.valueOf(itemap.get('id')) instanceof Id) && orderItemMap.containsKey(String.valueOf(itemap.get('id'))))
                    orderItem = orderItemMap.get((String)itemap.get('id'));//instanceof
                if(orderItem == Null){
                    orderItem = new OrderItem();
                    orderItem.product2 = orderItemss != null && orderItemss.size() >0 ?orderItemss[0].product2:null;
                    orderItem.product2Id = (String)itemap.get('product2Id');
                    orderItem.Order = orderItemss != null && orderItemss.size() >0 ?orderItemss[0].Order:null;
                    orderItem.Quantity = Integer.valueOf(itemap.get('reqQty'));
                    orderItem.Status__c = String.valueOf(itemap.get('status'));
                    System.debug('productIdToAssetMap :: '+productIdToAssetMap.get((String)itemap.get('product2Id')));
                    orderItem.Inventory_Tool__r = productIdToAssetMap.get((String)itemap.get('product2Id'));
                }
                orderItem.Schedule_Pick_Date__c = Date.valueOf((String)itemap.get('pickupDate'));
                orderItem.Schedule_Return_Date__c = Date.valueOf((String)itemap.get('retDate'));
                Decimal lowest = LowestQuantityCalculateClasss.lowestQuantityItemDate(orderItem, DateTime.now(), orderItemss);
                Decimal cQty = (Integer)itemap.get('confirmqty');
                system.debug('cQty :: '+cQty);
                if (cQty > lowest) {
                    itemIdToLowest.put(String.valueOf(itemap.get('id')), lowest); 
                    orderItem.Reserved_Quantity__c =  cQty;
                    orderItem.Lowest_Available_Quantity_For_this_Item__c = lowest;
                    itemListToReturn.add(orderItem); 
                }
            }
            return itemListToReturn;
      //  } catch (Exception e) {
        //    throw new AuraHandledException(e.getMessage());
        //}
    }


    @AuraEnabled
    public static List<OrderItem> getConflictedItems(String itemId, String affilliateId, String product2Id, Date pickupDate, Date returnDate){

        List<String> orderstatus = new List<String>{'Unconfirmed','Partially Confirmed','Confirmed','Fulfilled','Partially Returned','Overdue' };
         
        Map<String, OrderItem> orderToItemMap = new Map<String, OrderItem>();
        for(OrderItem item: [SELECT Id,product2Id,
                                        orderid,
                                        Order__c,
                                        LastModifiedDate,
                                        Quantity,
                                        order.EffectiveDate,
                                        Order.status,
                                        Order.Name,
                                        Order.Account.Name,
                                        Order.OrderNumber,
                                        Order.EndDate,
                                        PriceBookEntryId,
                                        Inventory_Tool__c,
                                        Affiliate_Handling_Fee__c,
                                        Inventory_Tool__r.Current_Inventory_F__c,
                                        Lowest_Available_Quantity_For_this_Item__c,
                                        Reserved_Quantity__c,
                                        Schedule_Pick_Date__c,
                                        Schedule_Return_Date__c 
                                        FROM OrderItem 
                                        WHERE product2Id =: product2Id 
                                        AND Schedule_Pick_Date__c <=: returnDate
                                        AND Schedule_Return_Date__c >=: pickupDate
                                        AND Product2.Type__c = 'Tool'
                                        AND Order.Affiliate__c =:affilliateId
                                        AND Order.status IN: orderstatus
                                        AND id !=: itemId
                                        ORDER BY Schedule_Return_Date__c ASC])
        {
            if(!orderToItemMap.containsKey(item.orderid)){
                orderToItemMap.put(item.orderid, item);
            }
            
            orderItem line = orderToItemMap.get(item.orderid);
            if(line.Id != item.Id){
                line.quantity += item.quantity != null? item.quantity:0;
                line.Reserved_Quantity__c += item.Reserved_Quantity__c != null? item.Reserved_Quantity__c:0;
            }
            line.Schedule_Pick_Date__c = item.order.EffectiveDate;
            line.Schedule_Return_Date__c = item.Schedule_Return_Date__c;

        }
        

        return orderToItemMap.values();
    }
}