force-app/main/default/objects/Account/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Affiliate Handling Fee</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Desired_Pickup_Date__c.field-meta.xml
<CustomField>
    <fullName>Desired_Pickup_Date__c</fullName>
    <label>Desired Pickup Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Desired_Pickup_Time__c.field-meta.xml
<CustomField>
    <fullName>Desired_Pickup_Time__c</fullName>
    <label>Desired Pickup Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>9:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:30 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:30 PM</fullName>
            </value>
            <value>
                <fullName>3:00 PM</fullName>
            </value>
            <value>
                <fullName>3:30 PM</fullName>
            </value>
            <value>
                <fullName>4:00 PM</fullName>
            </value>
            <value>
                <fullName>4:30 PM</fullName>
            </value>
            <value>
                <fullName>5:00 PM</fullName>
            </value>
            <value>
                <fullName>5:30 PM</fullName>
            </value>
            <value>
                <fullName>6:00 PM</fullName>
            </value>
            <value>
                <fullName>6:30 PM</fullName>
            </value>
            <value>
                <fullName>7:00 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Late_Fee__c.field-meta.xml
<CustomField>
    <fullName>Late_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Late Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Requested_Borrowing_Period__c.field-meta.xml
<CustomField>
    <fullName>Requested_Borrowing_Period__c</fullName>
    <label>Requested Borrowing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 week</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
            </value>
            <value>
                <fullName>3 weeks</fullName>
            </value>
            <value>
                <fullName>4 weeks</fullName>
            </value>
            <value>
                <fullName>5 weeks</fullName>
            </value>
            <value>
                <fullName>6 weeks</fullName>
            </value>
            <value>
                <fullName>7 weeks</fullName>
            </value>
            <value>
                <fullName>8 weeks</fullName>
            </value>
            <value>
                <fullName>9 weeks</fullName>
            </value>
            <value>
                <fullName>10 weeks</fullName>
            </value>
            <value>
                <fullName>11 weeks</fullName>
            </value>
            <value>
                <fullName>12 weeks</fullName>
            </value>
            <value>
                <fullName>13 weeks</fullName>
            </value>
            <value>
                <fullName>14 weeks</fullName>
            </value>
            <value>
                <fullName>15 weeks</fullName>
            </value>
            <value>
                <fullName>16 weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Schedule_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Return_Date__c</fullName>
    <label>Schedule Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Scheduled_Pickup_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Pickup_Time__c</fullName>
    <label>Scheduled Pickup Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tools_Returned_By__c.field-meta.xml
<CustomField>
    <fullName>Tools_Returned_By__c</fullName>
    <label>Tools Returned By</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Actual_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Return_Date__c</fullName>
    <label>Actual Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <label>Affiliate Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Check_In_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Check In Quantity</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Check_Out_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Quantity__c</fullName>
    <label>Check Out Quantity</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Damaged__c.field-meta.xml
<CustomField>
    <fullName>Damaged__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Damaged</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Inventory_Tool__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Tool__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Order Tool</relationshipLabel>
    <relationshipName>Order_Tools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Late_Fee__c.field-meta.xml
<CustomField>
    <fullName>Late_Fee__c</fullName>
    <formula>2*Late_Weeks__c * UnitPrice * Quantity * Affiliate_Handling_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Late Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Lost__c.field-meta.xml
<CustomField>
    <fullName>Lost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lost</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Requested_Borrowing_Period__c.field-meta.xml
<CustomField>
    <fullName>Requested_Borrowing_Period__c</fullName>
    <label>Requested Borrowing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 week</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
            </value>
            <value>
                <fullName>3 weeks</fullName>
            </value>
            <value>
                <fullName>4 weeks</fullName>
            </value>
            <value>
                <fullName>5 weeks</fullName>
            </value>
            <value>
                <fullName>6 weeks</fullName>
            </value>
            <value>
                <fullName>7 weeks</fullName>
            </value>
            <value>
                <fullName>8 weeks</fullName>
            </value>
            <value>
                <fullName>9 weeks</fullName>
            </value>
            <value>
                <fullName>10 weeks</fullName>
            </value>
            <value>
                <fullName>11 weeks</fullName>
            </value>
            <value>
                <fullName>12 weeks</fullName>
            </value>
            <value>
                <fullName>13 weeks</fullName>
            </value>
            <value>
                <fullName>14 weeks</fullName>
            </value>
            <value>
                <fullName>15 weeks</fullName>
            </value>
            <value>
                <fullName>16 weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Reserved_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Reserved_Quantity__c</fullName>
    <label>Confirmed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Schedule_Pick_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Pick_Date__c</fullName>
    <label>Schedule Pick Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Schedule_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Return_Date__c</fullName>
    <label>Schedule Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unconfirmed</fullName>
                <default>true</default>
                <label>Unconfirmed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Partially Returned</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>OverDue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
                <isActive>false</isActive>
                <label>Damaged</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Partially confirmed</fullName>
                <isActive>false</isActive>
                <label>Partially confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tool_Handling_Fee_Per_Item__c.field-meta.xml
<CustomField>
    <fullName>Tool_Handling_Fee_Per_Item__c</fullName>
    <formula>Affiliate_Handling_Fee__c * UnitPrice*1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tool Handling Fee Per Item</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_Check_In_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Check_In_Quantity__c</fullName>
    <formula>NULLVALUE(Check_In_Quantity__c, 0)  +  NULLVALUE(Damaged__c, 0) +  NULLVALUE(Lost__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Check In Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tool_Note__c.field-meta.xml
<CustomField>
    <fullName>Tool_Note__c</fullName>
    <label>Tool Note</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tool</fullName>
            </value>
            <value>
                <fullName>Additional Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReturnOrderController.cls
public class ReturnOrderController {

    @AuraEnabled(cacheable = true)
    public static OrderDetails getOrderItems(String orderId) {
        return getOrderItemsDirect(orderId);
    }

    @AuraEnabled
    public static OrderDetails getOrderItemsDirect(String orderId) {
        try {

            OrderDetails orderDetail = new OrderDetails();
            orderDetail.orderItems = new List<OrderItemDetails>();
            orderDetail.returnOrderItems = new List<OrderItemDetails>();
            for(Order ord: [SELECT Id, name,Account.Name,Desired_Pickup_Date__c,
                    Desired_Pickup_Time__c,OrderNumber,CreatedDate,EffectiveDate,
                    Scheduled_Pickup_Time__c,Schedule_Return_Date__c,EndDate,Status,
                    (SELECT Id,
                    Product2.Name,
                    Tool_Handling_Fee_Per_Item__c,
                    Status__c,
                    Check_In_Quantity__c,
                    Product2.Tool_Note__c,
                    Check_Out_Quantity__c,
                    Total_Check_In_Quantity__c,
                    Actual_Return_Date__c,
                    Lost__c,
                    late_Fee__c,
                    Damaged__c,
                    Inventory_Tool__c,
                    UnitPrice,
                    Product2Id,
                    PricebookEntryId,
                    Affiliate_Handling_Fee__c,
                    Requested_Borrowing_Period__c,
                    Schedule_Return_Date__c
                    FROM OrderItems 
                    WHERE Product2.Type__c ='Tool'
                    AND Status__c != 'Unavailable'
                    ORDER BY Product2.Name ) 
                    FROM ORDER WHERE Id =: orderId]){
                orderDetail.order = ord;
                if( !'Fulfilled'.equalsIgnoreCase(ord.status) && !'Partially Returned'.equalsIgnoreCase(ord.status) && !'Overdue'.equalsIgnoreCase(ord.status)){
                    orderDetail.readOnly = true;
                }
                for(OrderItem item: ord.OrderItems){
                    OrderItemDetails orditem = new OrderItemDetails();
                    orditem.orderitem = item;
                    Decimal borrowed = item.Check_Out_Quantity__c!= null?item.Check_Out_Quantity__c:0;
                    Decimal totalReturned = item.Total_Check_In_Quantity__c!= null?item.Total_Check_In_Quantity__c:0;
                    Decimal lost = item.Lost__c!= null?item.Lost__c:0;
                    orditem.stillOut = Integer.valueOf(borrowed-totalReturned);
                    orditem.lost = (item.unitPrice*lost).setScale(2);
                    //if(item.Schedule_Return_Date__c < Date.today())
                        orditem.late = item.late_Fee__c.setScale(2);
                   // else orditem.late =0;
                    orditem.total = (orditem.lost + orditem.late).setScale(2);
                    orditem.fixed = item.status__c;
                    orditem.isReturned = item.status__c == 'Returned'?true:false;

                    if(item.status__c == 'Returned')
                        orderDetail.returnOrderItems.add(orditem);
                    else orderDetail.orderItems.add(orditem);

                }
            }
            return orderDetail;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string saveOrder(String itemsList){
       // try {
            system.debug(itemsList);
            List<Object> ordItemList = (List<Object>) json.deserializeUntyped(itemsList);
            list<OrderItem> orderItemList = new List<orderItem>();
            list<Date> orderItemReturnDateList = new List<Date>();
            String returnedBy;
            String orderid;
            Set<String> orderToolIdsSet = new Set<String>();
            
            for(Object obj:ordItemList){
                Map<String, Object> item = (Map<String, Object>)obj;
                OrderItem orderItem = new OrderItem();
                String itemId = (string)item.get('Id');
                returnedBy = (String)item.get('returnedBy');
                orderid = (string)item.get('orderid');
                orderToolIdsSet.add(itemId);
                if(itemId != '2'){
                    orderItem.id = itemId;
                }else{
                    orderItem.Inventory_Tool__c  =(string)item.get('assetid');   
                    orderItem.unitPrice =Decimal.valueOf((String)item.get('unitPrice'));
                    //product2id:product2id,
                    
                    orderitem.orderid = (string)item.get('orderid');
                    orderItem.pricebookEntryId = (string)item.get('pbeid');
                    orderItem.Affiliate_Handling_Fee__c = Decimal.valueOf((String)item.get('affiliatefee'));
                    
                }

                if(item.containsKey('borrowed')){
                    orderitem.quantity = Decimal.valueOf((Integer)item.get('borrowed'));
                    orderitem.Reserved_Quantity__c = Decimal.valueOf((Integer)item.get('borrowed'));
                }

                //OrderItem/returnDate:returnDate,
                Decimal lost = Decimal.valueOf((Integer)item.get('lost'));
                Decimal damaged = Decimal.valueOf( (Integer)item.get('damaged'));
                Decimal returnqty = Decimal.valueOf((Integer)item.get('returnqty'));

                if(lost != Null && lost !=0)
                    orderItem.Lost__c= lost;
                if(damaged != Null && damaged !=0)
                    orderItem.damaged__c =damaged;
                if(returnqty != Null && returnqty !=0)
                    orderItem.Check_In_Quantity__c = returnqty;

                orderItem.Requested_Borrowing_Period__c = (string)item.get('borrowedPeriod');

                orderItem.status__c = (String)item.get('status');

                if('Returned'.equalsIgnoreCase(OrderItem.status__c))
                    orderItem.Actual_Return_Date__c = system.today();
                orderItem.Schedule_Return_Date__c = Date.valueOf((String)item.get('returnDate'));
                orderItemReturnDateList.add(orderItem.Schedule_Return_Date__c);
                orderItem.Schedule_Pick_Date__c = Date.valueOf((String)item.get('EffectiveDate'));
                //basefee:basefee,
                Decimal borrowed = Decimal.valueOf((Integer)item.get('borrowed'));
                if(borrowed != Null && borrowed !=0)
                    OrderItem.Check_Out_Quantity__c= borrowed;

                orderItemList.add(orderitem);
            }
            

            if(String.isNotBlank(orderid) ){
                Order order = new order( id=orderid);
                if( String.isNotBlank(returnedBy))
                    order.Tools_Returned_By__c=returnedBy;
                if(orderItemReturnDateList.size()>0){
                    orderItemReturnDateList.sort();
                    order.EndDate = orderItemReturnDateList[0];
                }
                ByPassValidations.ordStatusValidation = true;
                update order;
            }
            ByPassValidations.ordItemPriceAndQtyValidation = true;
            if(!orderItemList.isEmpty())
                upsert orderItemList;

            return 'success';
    }

    public class OrderDetails{

        @AuraEnabled
        public Order order;
        @AuraEnabled
        public Boolean readOnly;
        @AuraEnabled
        public List<OrderItemDetails> orderItems;
        @AuraEnabled
        public List<OrderItemDetails> returnOrderItems;
    }

    public class OrderItemDetails{

       
        @AuraEnabled
        public OrderItem orderItem;
        @AuraEnabled
        public Integer stillOut;
        @AuraEnabled
        public Decimal lost;
        @AuraEnabled
        public Decimal late;
        @AuraEnabled
        public Decimal total;
        @AuraEnabled
        public String fixed;
        @AuraEnabled
        public Boolean isReturned;


    }
}