force-app/main/default/objects/Account/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Affiliate Handling Fee</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <formula>Account.Affiliate_Handling_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Affiliate Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Current_Inventory_F__c.field-meta.xml
<CustomField>
    <fullName>Current_Inventory_F__c</fullName>
    <formula>Quantity -( Damaged_F__c  +  Maintenance_F__c + Other_R__c +  Rebranding_F__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field includes On Shelf and Out but not including Rebranding/Maintenance, Damaged, Other.</inlineHelpText>
    <label>Current Inventory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <formula>TEXT(Product2.Sub_Category__c )</formula>
    <label>Sub-Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Unlisted_Item__c.field-meta.xml
<CustomField>
    <fullName>Unlisted_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unlisted Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <description>The affiliate to which the contact is most closely connected.</description>
    <inlineHelpText>Select the affiliate to which the contact is most closely connected.  Go to www.toolbank.org/citycodes to view a city code list.</inlineHelpText>
    <label>Affiliate</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ATL</fullName>
            </value>
            <value>
                <fullName>BLT</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>CIN</fullName>
            </value>
            <value>
                <fullName>CLT</fullName>
            </value>
            <value>
                <fullName>DEN</fullName>
            </value>
            <value>
                <fullName>DET</fullName>
            </value>
            <value>
                <fullName>HFD</fullName>
            </value>
            <value>
                <fullName>HOU</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NWK</fullName>
            </value>
            <value>
                <fullName>PDX</fullName>
            </value>
            <value>
                <fullName>PHX</fullName>
            </value>
            <value>
                <fullName>RVA</fullName>
            </value>
            <value>
                <fullName>SAT</fullName>
            </value>
            <value>
                <fullName>SAV</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
                <default>true</default>
                <label>USA</label>
            </value>
            <value>
                <fullName>WDC</fullName>
            </value>
            <value>
                <fullName>WNS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(User__c ==null , &apos;User Not Created&apos; , IF(User__c !=null &amp;&amp; User__r.IsActive, &apos;Active&apos;, &apos;Inactive&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Actual_Pickup_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Pickup_Date_Time__c</fullName>
    <label>Actual Pickup Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliate</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliate Orders</relationshipLabel>
    <relationshipName>AffiliateOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Desired_Pickup_Date__c.field-meta.xml
<CustomField>
    <fullName>Desired_Pickup_Date__c</fullName>
    <label>Desired Pickup Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Desired_Pickup_Time__c.field-meta.xml
<CustomField>
    <fullName>Desired_Pickup_Time__c</fullName>
    <label>Desired Pickup Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>9:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:30 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:30 PM</fullName>
            </value>
            <value>
                <fullName>3:00 PM</fullName>
            </value>
            <value>
                <fullName>3:30 PM</fullName>
            </value>
            <value>
                <fullName>4:00 PM</fullName>
            </value>
            <value>
                <fullName>4:30 PM</fullName>
            </value>
            <value>
                <fullName>5:00 PM</fullName>
            </value>
            <value>
                <fullName>5:30 PM</fullName>
            </value>
            <value>
                <fullName>6:00 PM</fullName>
            </value>
            <value>
                <fullName>6:30 PM</fullName>
            </value>
            <value>
                <fullName>7:00 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Requested_Borrowing_Period__c.field-meta.xml
<CustomField>
    <fullName>Requested_Borrowing_Period__c</fullName>
    <label>Requested Borrowing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 week</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
            </value>
            <value>
                <fullName>3 weeks</fullName>
            </value>
            <value>
                <fullName>4 weeks</fullName>
            </value>
            <value>
                <fullName>5 weeks</fullName>
            </value>
            <value>
                <fullName>6 weeks</fullName>
            </value>
            <value>
                <fullName>7 weeks</fullName>
            </value>
            <value>
                <fullName>8 weeks</fullName>
            </value>
            <value>
                <fullName>9 weeks</fullName>
            </value>
            <value>
                <fullName>10 weeks</fullName>
            </value>
            <value>
                <fullName>11 weeks</fullName>
            </value>
            <value>
                <fullName>12 weeks</fullName>
            </value>
            <value>
                <fullName>13 weeks</fullName>
            </value>
            <value>
                <fullName>14 weeks</fullName>
            </value>
            <value>
                <fullName>15 weeks</fullName>
            </value>
            <value>
                <fullName>16 weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Schedule_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Return_Date__c</fullName>
    <label>Schedule Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Scheduled_Pickup_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Pickup_Time__c</fullName>
    <label>Scheduled Pickup Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tools_Picked_Up_By__c.field-meta.xml
<CustomField>
    <fullName>Tools_Picked_Up_By__c</fullName>
    <label>Tools Picked Up By</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Actual_Pickup_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Pickup_Date_Time__c</fullName>
    <formula>Order.Actual_Pickup_Date_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Pickup Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <label>Affiliate Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Inventory_Tool__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Tool__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Order Tool</relationshipLabel>
    <relationshipName>Order_Tools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Lowest_Available_Quantity_For_this_Item__c.field-meta.xml
<CustomField>
    <fullName>Lowest_Available_Quantity_For_this_Item__c</fullName>
    <description>Test Field will be removed later if needed</description>
    <label>Lowest Available Quantity For this Item</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Requested_Borrowing_Period__c.field-meta.xml
<CustomField>
    <fullName>Requested_Borrowing_Period__c</fullName>
    <label>Requested Borrowing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 week</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
            </value>
            <value>
                <fullName>3 weeks</fullName>
            </value>
            <value>
                <fullName>4 weeks</fullName>
            </value>
            <value>
                <fullName>5 weeks</fullName>
            </value>
            <value>
                <fullName>6 weeks</fullName>
            </value>
            <value>
                <fullName>7 weeks</fullName>
            </value>
            <value>
                <fullName>8 weeks</fullName>
            </value>
            <value>
                <fullName>9 weeks</fullName>
            </value>
            <value>
                <fullName>10 weeks</fullName>
            </value>
            <value>
                <fullName>11 weeks</fullName>
            </value>
            <value>
                <fullName>12 weeks</fullName>
            </value>
            <value>
                <fullName>13 weeks</fullName>
            </value>
            <value>
                <fullName>14 weeks</fullName>
            </value>
            <value>
                <fullName>15 weeks</fullName>
            </value>
            <value>
                <fullName>16 weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Reserved_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Reserved_Quantity__c</fullName>
    <label>Confirmed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Schedule_Pick_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Pick_Date__c</fullName>
    <label>Schedule Pick Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Schedule_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Return_Date__c</fullName>
    <label>Schedule Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Tool_Note__c.field-meta.xml
<CustomField>
    <fullName>Tool_Note__c</fullName>
    <label>Tool Note</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tool</fullName>
            </value>
            <value>
                <fullName>Additional Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sub_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A-frame</fullName>
    </customValue>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Augers</fullName>
    </customValue>
    <customValue>
        <fullName>Batteries</fullName>
    </customValue>
    <customValue>
        <fullName>Blowers</fullName>
    </customValue>
    <customValue>
        <fullName>Brush clearing/chainsaws</fullName>
    </customValue>
    <customValue>
        <fullName>Buckets</fullName>
    </customValue>
    <customValue>
        <fullName>Carts</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaning</fullName>
    </customValue>
    <customValue>
        <fullName>Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Cutting</fullName>
    </customValue>
    <customValue>
        <fullName>Decorations &amp; Lighting</fullName>
    </customValue>
    <customValue>
        <fullName>Demolition</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Digging</fullName>
    </customValue>
    <customValue>
        <fullName>Dolly/Hand Trucks</fullName>
    </customValue>
    <customValue>
        <fullName>Drills</fullName>
    </customValue>
    <customValue>
        <fullName>Drywall &amp; Masonry</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Fans &amp; Heaters</fullName>
    </customValue>
    <customValue>
        <fullName>Food &amp; Beverage</fullName>
    </customValue>
    <customValue>
        <fullName>Forks</fullName>
    </customValue>
    <customValue>
        <fullName>Games &amp; Recreation</fullName>
    </customValue>
    <customValue>
        <fullName>Generators</fullName>
    </customValue>
    <customValue>
        <fullName>Gloves</fullName>
    </customValue>
    <customValue>
        <fullName>Hammers &amp; Chisels</fullName>
    </customValue>
    <customValue>
        <fullName>Hoses</fullName>
    </customValue>
    <customValue>
        <fullName>Invasive removal</fullName>
    </customValue>
    <customValue>
        <fullName>Jacks</fullName>
    </customValue>
    <masterLabel>Sub-Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConfirmOrderPageController.cls
public class ConfirmOrderPageController {
    
    @AuraEnabled(cacheable=true)
    public static OrderDetails getOrderDetails(String recordId){

        return getOrderDetailsDirect(recordId);
    }

    @AuraEnabled(cacheable=true)
    public static String getTimeZone(){
        TimeZone tz = UserInfo.getTimeZone();
        return tz.getID();
    }

    @AuraEnabled
    public static OrderDetails getOrderDetailsDirect(String recordId){

        List<Order> order = [SELECT Id,Account.name,Affiliate__c,Tools_Picked_Up_By__c,Status,Actual_Pickup_Date_Time__c, Requested_Borrowing_Period__c,createdDate,name,Schedule_Return_Date__c,EndDate, OrderNumber,Desired_Pickup_Date__c,Desired_Pickup_Time__c,EffectiveDate,Scheduled_Pickup_Time__c FROM Order WHERE Id =: recordId];
        OrderDetails OrderDetails = new OrderDetails();
        OrderDetails.order = order[0];
        Long milliseconds = system.now().getTime() - (order[0].Actual_Pickup_Date_Time__c != Null ?order[0].Actual_Pickup_Date_Time__c.getTime():system.now().getTime());
        Long seconds = milliseconds / 1000;
        Long minutes = seconds / 60;
        Long hours = minutes / 60;
        OrderDetails.readOnly = (hours) >=2; 
        List<OrderItem> OrderItemList =LowestQuantityCalculateClasss.lowestQuantityOrder3(order);
        if(OrderItemList != Null && OrderItemList.size()>0){
            
            Map<Decimal, list<OrderItem>> availablesorting = new map<Decimal, list<OrderItem>>();
            List<Decimal> sortList = new List<Decimal>();
        // system.debug(OrderItemList.size());

            for(OrderItem item: OrderItemList){
                Decimal diff = item.Lowest_Available_Quantity_For_this_Item__c - item.Reserved_Quantity__c;
                if(!sortList.contains(diff))
                    sortList.add(diff);

                if(!availablesorting.containsKey(diff))
                    availablesorting.put(diff, new list<OrderItem>());
                    
                availablesorting.get(diff).add(item);
                system.debug(item);
            }
        system.debug(availablesorting);
            sortList.sort();
           
            OrderDetails.orderItemList = new List<OrderItem>();
            for(Decimal diff: sortList){
                OrderDetails.orderItemList.addAll(availablesorting.get(diff));
            }
            system.debug(OrderDetails.orderItemList.size());

        }
            return OrderDetails;
        
    }

    @AuraEnabled(cacheable=true)
    public static List<AvailableProducts> getTools(List<String> toolIds, String accid, String searchString,String category){
        system.debug(toolIds);
        //String accid = [SELECT Id, Contact.Account.parentId FROM User WHERE Id =: UserInfo.getUserId()].Contact.Account.parentId;
        system.debug(accId);


        List<Asset> assetList;
        if(String.isBlank(searchString) && String.isBlank(category)){
            assetList = [SELECT Id,Affiliate_Handling_Fee__c,
                        Product2Id,
                        price 
                        FROM Asset 
                        WHERE AccountId =: accid
                        AND Unlisted_Item__c = false
                        AND Product2Id  NOT IN: toolIds
                        AND Product2.Type__c = 'Tool'
                        AND (Quantity != Null 
                        OR Quantity != 0)];
        }else{
            if(String.isNotBlank(searchString))
                searchString = '%'+searchString+'%';
            if(String.isBlank(category) && String.isNotBlank(searchString)){
                assetList = [SELECT Id,Affiliate_Handling_Fee__c,
                            Product2Id,
                            price 
                            FROM Asset 
                            WHERE AccountId =: accid
                            AND Unlisted_Item__c = false
                            AND (Product2.name like: searchString
                            OR Product2.productCode like:searchString
                            OR Product2.Tool_Note__c like:searchString)
                            AND Product2Id  NOT IN: toolIds
                            AND Product2.Type__c = 'Tool'
                            AND (Quantity != Null 
                            OR Quantity != 0)];
            }
            else if(String.isNotBlank(category) && String.isBlank(searchString)){
                if(category == 'All'){
                    assetList = [SELECT Id,Affiliate_Handling_Fee__c,
                    Product2Id,
                    price 
                    FROM Asset 
                    WHERE AccountId =: accid
                    AND Unlisted_Item__c = false
                    AND Product2Id  NOT IN: toolIds
                    AND Product2.Type__c = 'Tool'
                    AND (Quantity != Null 
                    OR Quantity != 0)];
                }else{
                    assetList = [SELECT Id,Affiliate_Handling_Fee__c,
                            Product2Id,
                            price 
                            FROM Asset 
                            WHERE AccountId =: accid
                            AND Product2.Family =: category
                            AND Unlisted_Item__c = false
                            AND Product2Id  NOT IN: toolIds
                            AND Product2.Type__c = 'Tool'
                            AND (Quantity != Null 
                            OR Quantity != 0)];
                }
                
            }
            else if(String.isNotBlank(category) && String.isNotBlank(searchString)){

                if(category == 'All'){
                    assetList = [SELECT Id,Affiliate_Handling_Fee__c,
                    Product2Id,
                    price 
                    FROM Asset 
                    WHERE AccountId =: accid
                    AND Unlisted_Item__c = false
                    AND (Product2.name like: searchString
                    OR Product2.productCode like:searchString
                    OR Product2.Tool_Note__c like:searchString)
                    AND Product2Id  NOT IN: toolIds
                    AND Product2.Type__c = 'Tool'
                    AND (Quantity != Null 
                    OR Quantity != 0)];
                }else{
                assetList = [SELECT Id,Affiliate_Handling_Fee__c,
                            Product2Id,
                            price 
                            FROM Asset 
                            WHERE AccountId =: accid
                            AND Unlisted_Item__c = false
                            AND (Product2.name like: searchString
                            OR Product2.productCode like:searchString
                            OR Product2.Tool_Note__c like:searchString)
                            AND product2.Family =: category
                            AND Product2Id  NOT IN: toolIds
                            AND Product2.Type__c = 'Tool'
                            AND (Quantity != Null 
                            OR Quantity != 0)];
                }
            }
        }

        Set<Id> productidSet = new Set<Id>();
        Map<id, Asset> productIdToAssetMap = new map<Id, Asset>();
        for(Asset asset:  assetList){
            productidSet.add(asset.product2Id);
            productIdToAssetMap.put(asset.Product2Id, asset);
        }
        
        List<AvailableProducts> availableProducts = new List<AvailableProducts>();
        for(PriceBookEntry pbe: [SELECT Id,
                                        Product2Id,
                                        UnitPrice,
                                        Product2.Tool_Note__c, 
                                        Product2.Sub_Category__c,
                                        Product2.Name, 
                                        Product2.Family 
                                        FROM PriceBookEntry 
                                        WHERE Product2Id IN: productidSet
                                        AND Pricebook2Id =: label.pricebookid]){
            AvailableProducts availableProduct = new AvailableProducts();
            availableProduct.Id = pbe.id;
            availableProduct.Product2Id =pbe.Product2Id;
            availableProduct.UnitPrice =pbe.UnitPrice;
            availableProduct.ToolNote= pbe.Product2.Tool_Note__c;
            availableProduct.SubCategory=pbe.Product2.Sub_Category__c;
            availableProduct.Name=pbe.Product2.Name;
            availableProduct.Family= pbe.Product2.Family;
            availableProduct.handlingFee = productIdToAssetMap.get(pbe.product2Id).Affiliate_Handling_Fee__c;
            availableProduct.AssetId = productIdToAssetMap.get(pbe.product2Id).Id;
            availableProducts.add(availableProduct);
        }
                                        
        return availableProducts;
    }

    @AuraEnabled
    public static Decimal singleItemLowestQuantity(String itemId, String product2Id, Date pickupDate, Date returnDate){

        system.debug('itemId '+itemId +' product2Id '+product2Id+' pickupDate '+pickupDate+' returnDate '+returnDate);
        List<OrderItem> allItemList =   [SELECT Id,product2Id,
                                        LastModifiedDate,Quantity,
                                        Affiliate_Handling_Fee__c,
                                        PriceBookEntryId,
                                        Inventory_Tool__c,
                                        Inventory_Tool__r.Current_Inventory_F__c,
                                        Lowest_Available_Quantity_For_this_Item__c,
                                        Reserved_Quantity__c,
                                        Schedule_Pick_Date__c,
                                        Schedule_Return_Date__c 
                                        FROM OrderItem 
                                        WHERE (product2Id =: product2Id 
                                        AND Schedule_Pick_Date__c <=: returnDate
                                        AND Schedule_Return_Date__c >=: pickupDate)
                                        OR Id =: itemId
                                        ORDER BY LastModifiedDate ASC];
        Map<Id, OrderItem> itemMap = new Map<Id, OrderItem>(allItemList);

        orderItem orderItem = itemMap.remove(itemId);
        orderItem.Schedule_Pick_Date__c = pickupDate;
        orderItem.Schedule_Return_Date__c = returnDate;
        system.debug('orderItem :: '+orderItem);
        system.debug('itemMap :: '+itemMap);

        return LowestQuantityCalculateClasss.lowestQuantityItemDate(orderItem, DateTime.now(), itemMap.values());
    }

    @AuraEnabled
    public static Map<String,Decimal> massDateChangeLowest(String orderItems){
        //try {
            
            system.debug(orderItems);
            list<object> itemList = (list<object>)JSON.deserializeUntyped(orderItems);
            system.debug(itemList);
            List<String> itemIdList = new List<String>();
            set<String> productIdSet = new set<String>();
            List<Date> dateList = new List<Date>();
            Id accountId;
            for(Object item: itemList){
                map<string, object> itemap = (map<string, object>)item;
                itemIdList.add(String.valueOf(itemap.get('id')));
                dateList.add(Date.valueOf((String)itemap.get('retDate')));
                dateList.add(Date.valueOf((String)itemap.get('pickupDate')));
                productIdSet.add((String)itemap.get('product2Id'));
                accountId = (String)itemap.get('accId');
            }
            system.debug(accountId);
            dateList.sort();
            Date minPickDate = dateList[0];
            Date maxReturnDate = dateList[dateList.size()-1];

            List<OrderItem> orderItemList =   [SELECT Id,product2Id,
                                        LastModifiedDate,Quantity,
                                        status__c,
                                        PriceBookEntryId,
                                        Affiliate_Handling_Fee__c,
                                        Inventory_Tool__c,
                                        Inventory_Tool__r.Current_Inventory_F__c,
                                        Lowest_Available_Quantity_For_this_Item__c,
                                        Reserved_Quantity__c,
                                        Schedule_Pick_Date__c,
                                        Schedule_Return_Date__c 
                                        FROM OrderItem 
                                        WHERE product2Id IN: productIdSet 
                                        AND Order.Affiliate__c =: accountId
                                        AND status__c != 'Returned'
                                        AND (Id  IN: itemIdList
                                        OR (Schedule_Pick_Date__c <=: maxReturnDate
                                        AND Schedule_Return_Date__c >=: minPickDate))
                                        ORDER BY LastModifiedDate ASC];
            Map<Id, OrderItem> orderItemMap = new Map<Id, OrderItem>(orderItemList);
            Map<id, List<OrderItem>> productIdToItemListMap =  new Map<Id, List<OrderItem>>();
            for(OrderItem item: orderItemList){
                if(!itemIdList.contains(item.id)){
                    if(!productIdToItemListMap.containsKey(item.product2Id))
                        productIdToItemListMap.put(item.product2Id, new List<OrderItem>());

                    productIdToItemListMap.get(item.product2Id).add(item);
                }
            }
            Map<id, Asset> productIdToAssetMap =  new Map<Id, Asset>();
            for(Asset asset: [SELECT Id,Product2Id,Current_Inventory_F__c FROM Asset WHERE accountId =: accountId and Product2Id IN:productIdSet]){
                productIdToAssetMap.put(asset.Product2Id, asset);
            }
            system.debug(productIdToAssetMap);
            Map<String,Decimal> itemIdToLowest = new map<String, Decimal>();
            for(Object item: itemList){
                map<string, object> itemap = (map<string, object>)item;
                List<OrderItem> orderItemss = productIdToItemListMap.get((String)itemap.get('product2Id'));
                OrderItem orderItem;
                system.debug(productIdToAssetMap.get((String)itemap.get('product2Id')));
                if((String.valueOf(itemap.get('id')) instanceof Id) && orderItemMap.containsKey(String.valueOf(itemap.get('id'))))
                    orderItem = orderItemMap.get((String)itemap.get('id'));//instanceof
                if(orderItem == Null){
                    orderItem = new OrderItem();
                    //orderItem.Id = (String)itemap.get('id');
                    orderItem.Inventory_Tool__r = productIdToAssetMap.get((String)itemap.get('product2Id'));
                }
                system.debug(orderItem);
                system.debug(orderItemss);
                orderItem.Schedule_Pick_Date__c = Date.valueOf((String)itemap.get('pickupDate'));
                orderItem.Schedule_Return_Date__c = Date.valueOf((String)itemap.get('retDate'));
                Decimal lowest = LowestQuantityCalculateClasss.lowestQuantityItemDate(orderItem, DateTime.now(), orderItemss);
                itemIdToLowest.put(String.valueOf(itemap.get('id')), lowest);   
            }
            return itemIdToLowest;
      //  } catch (Exception e) {
        //    throw new AuraHandledException(e.getMessage());
        //}
    }

    @AuraEnabled
    public static List<OrderItem> getConflictedItems(String itemId, String affilliateId, String product2Id, Date pickupDate, Date returnDate){

        List<String> orderstatus = new List<String>{'Unconfirmed','Partially Confirmed','Confirmed','Fulfilled','Partially Returned' };
         
        Map<String, OrderItem> orderToItemMap = new Map<String, OrderItem>();
        for(OrderItem item: [SELECT Id,product2Id,
                                        orderid,
                                        LastModifiedDate,
                                        Quantity,
                                        order.EffectiveDate,
                                        Order.status,
                                        Order.Name, 
                                        Order.OrderNumber,
                                        Order.EndDate,
                                        PriceBookEntryId,
                                        Inventory_Tool__c,
                                        Affiliate_Handling_Fee__c,
                                        Inventory_Tool__r.Current_Inventory_F__c,
                                        Lowest_Available_Quantity_For_this_Item__c,
                                        Reserved_Quantity__c,
                                        Schedule_Pick_Date__c,
                                        Schedule_Return_Date__c 
                                        FROM OrderItem 
                                        WHERE product2Id =: product2Id 
                                        AND Schedule_Pick_Date__c <=: returnDate
                                        AND Schedule_Return_Date__c >=: pickupDate
                                        AND Product2.Type__c = 'Tool'
                                        AND Order.Affiliate__c =:affilliateId
                                        AND Order.status IN: orderstatus
                                        AND id !=: itemId
                                        ORDER BY Schedule_Return_Date__c ASC])
        {
            if(!orderToItemMap.containsKey(item.orderid))
                orderToItemMap.put(item.orderid, new OrderItem(quantity=0,Reserved_Quantity__c=0, order=item.order));
            
            orderItem line = orderToItemMap.get(item.orderid);
            line.quantity += item.quantity != null? item.quantity:0;
            line.Reserved_Quantity__c += item.Reserved_Quantity__c != null? item.Reserved_Quantity__c:0;
            line.Schedule_Pick_Date__c = item.order.EffectiveDate;
            line.Schedule_Return_Date__c = item.Schedule_Return_Date__c;

        }
        

        return orderToItemMap.values();
    }

    @AuraEnabled
    public static string saveOrder(String orderNitemsDetails, String orderItemToDelete){
        system.debug(orderNitemsDetails);
        Map<String, object> orderAndItemDetails = (Map<String, object>)JSON.deserializeUntyped(orderNitemsDetails);
        Map<String, Object> order = (Map<String, Object>)orderAndItemDetails.get('order');
        
        if(String.isNotBlank(orderItemToDelete)){
            List<object> ItemToDelete = (List<object>)JSON.deserializeUntyped(orderItemToDelete);
            List<OrderItem> toolsToDelete = new List<OrderItem>();
            for(Object obj: ItemToDelete){
                String id = (String)obj;
                if(id.startsWith('802')){
                    toolsToDelete.add(new OrderItem(Id=id));
                }
            }
            if(!toolsToDelete.isEmpty())
                delete toolsToDelete;
        }
system.debug(order.get('Scheduled_Pickup_Time__c'));
Time pickTime;
if(order.get('Scheduled_Pickup_Time__c') != null && String.isNotBlank(((String)order.get('Scheduled_Pickup_Time__c')).trim())){
    List<String> timeString = Test.isRunningTest()?'02:45 PM'.split(':'):((String)order.get('Scheduled_Pickup_Time__c')).split(':');
    if(timeString != null && timeString.size() >0){
        Integer hour = Integer.valueOf(timeString[0]);
        Integer minutes = Integer.valueOf(timeString[1].split(' ')[0]);
        String AMPM = timeString[1].split(' ')[1];
        if(AMPM == 'AM' && hour == 12)
            hour = hour-12;
        else if(AMPM == 'PM')
            hour = hour+12;
    system.debug(hour+':'+minutes);
    pickTime = Time.newInstance(hour,minutes,0,0);
    }
}
        Order updateOrder =  new order(
            id= (Id)order.get('Id'),
            EffectiveDate = Date.valueOf((String)order.get('EffectiveDate')),
            Tools_Picked_Up_By__c = (String)order.get('Tools_Picked_Up_By__c'),
            Scheduled_Pickup_Time__c = pickTime,
            EndDate =  Date.valueOf((String)order.get('EndDate')),
            name =  (String)order.get('Name'),
            status = (String)order.get('Status'),
            pricebook2Id = label.pricebookid
        );
        if((String)order.get('Status') == 'Fulfilled')
        updateOrder.Actual_Pickup_Date_Time__c = system.now();

        update updateOrder;
        
        list<OrderItem> orderitems = new List<OrderItem>();
        for(object obj: (List<Object>)orderAndItemDetails.get('orderItems')){
            Map<String, object> item = (Map<String, object>)obj;
            system.debug(item);
            OrderItem orderitem = new OrderItem();
            if(((String) item.get('Id')).startsWith('802')){
                orderItem.id = (String) item.get('Id');
            }else{
                orderItem.orderid= (String)order.get('Id');
                orderItem.PricebookEntryId = (String)item.get('pbeId');
                orderitem.UnitPrice = Decimal.valueOf((String)item.get('unitprice'));
                orderItem.Inventory_Tool__c = (String)item.get('assetid');
            }
            orderItem.quantity =Decimal.valueOf((String) item.get('quantity'));
            orderItem.Affiliate_Handling_Fee__c =Decimal.valueOf((String) item.get('affiliateFee'));
            orderItem.Requested_Borrowing_Period__c = (String) item.get('week');
            orderItem.Reserved_Quantity__c=Decimal.valueOf((String) item.get('reserv'));
            orderItem.Schedule_return_Date__c = Date.valueOf((String)item.get('retDate'));
            orderItem.Schedule_Pick_Date__c = Date.valueOf((String)item.get('pickdate'));
            orderItem.Status__c = (String) item.get('status');
            system.debug(orderitem);
            if((String) item.get('status') == 'Fulfilled')
                orderItem.Check_Out_Quantity__c=Decimal.valueOf((String) item.get('reserv'));

            orderitems.add(orderitem);
        }

        upsert orderitems;

        return 'success';
    }

    public class OrderDetails{
        @AuraEnabled
        public Order order;
        @AuraEnabled
        public Boolean readOnly;
        @AuraEnabled
        public List<OrderItem> orderItemList;
    }

    public class AvailableProducts{
        @AuraEnabled
        public String Id;
        @AuraEnabled
        public String  Product2Id;
        @AuraEnabled
        public Decimal UnitPrice;
        @AuraEnabled
        public String ToolNote;
        @AuraEnabled 
        public String  SubCategory;
        @AuraEnabled
        public String Name;
        @AuraEnabled 
        public String Family;
        @AuraEnabled 
        public String AssetId;  
        @AuraEnabled 
        public Decimal handlingFee;

    }
}