force-app/main/default/objects/Account/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Affiliate Handling Fee</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Affiliate.recordType-meta.xml
<RecordType>
    <fullName>Affiliate</fullName>
    <active>true</active>
    <description>Affiliate Account</description>
    <label>Affiliate</label>
</RecordType>

force-app/main/default/objects/Affiliate_Account__c/Affiliate_Account__c.object-meta.xml
<CustomObject>
    <label>Affiliate Account</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Affiliate Account No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliate Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Account__c/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <label>Affiliate</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliate Users</relationshipLabel>
    <relationshipName>Affiliate_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <description>The affiliate to which the contact is most closely connected.</description>
    <inlineHelpText>Select the affiliate to which the contact is most closely connected.  Go to www.toolbank.org/citycodes to view a city code list.</inlineHelpText>
    <label>Affiliate</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ATL</fullName>
            </value>
            <value>
                <fullName>BLT</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>CIN</fullName>
            </value>
            <value>
                <fullName>CLT</fullName>
            </value>
            <value>
                <fullName>DEN</fullName>
            </value>
            <value>
                <fullName>DET</fullName>
            </value>
            <value>
                <fullName>HFD</fullName>
            </value>
            <value>
                <fullName>HOU</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NWK</fullName>
            </value>
            <value>
                <fullName>PDX</fullName>
            </value>
            <value>
                <fullName>PHX</fullName>
            </value>
            <value>
                <fullName>RVA</fullName>
            </value>
            <value>
                <fullName>SAT</fullName>
            </value>
            <value>
                <fullName>SAV</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
                <default>true</default>
                <label>USA</label>
            </value>
            <value>
                <fullName>WDC</fullName>
            </value>
            <value>
                <fullName>WNS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(User__c ==null , &apos;User Not Created&apos; , IF(User__c !=null &amp;&amp; User__r.IsActive, &apos;Active&apos;, &apos;Inactive&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit__c/Credit__c.object-meta.xml
<CustomObject>
    <label>Credit</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Credit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credits</relationshipLabel>
    <relationshipName>Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliate</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliate Orders</relationshipLabel>
    <relationshipName>AffiliateOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Desired_Pickup_Date__c.field-meta.xml
<CustomField>
    <fullName>Desired_Pickup_Date__c</fullName>
    <label>Desired Pickup Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Requested_Borrowing_Period__c.field-meta.xml
<CustomField>
    <fullName>Requested_Borrowing_Period__c</fullName>
    <label>Requested Borrowing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 week</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
            </value>
            <value>
                <fullName>3 weeks</fullName>
            </value>
            <value>
                <fullName>4 weeks</fullName>
            </value>
            <value>
                <fullName>5 weeks</fullName>
            </value>
            <value>
                <fullName>6 weeks</fullName>
            </value>
            <value>
                <fullName>7 weeks</fullName>
            </value>
            <value>
                <fullName>8 weeks</fullName>
            </value>
            <value>
                <fullName>9 weeks</fullName>
            </value>
            <value>
                <fullName>10 weeks</fullName>
            </value>
            <value>
                <fullName>11 weeks</fullName>
            </value>
            <value>
                <fullName>12 weeks</fullName>
            </value>
            <value>
                <fullName>13 weeks</fullName>
            </value>
            <value>
                <fullName>14 weeks</fullName>
            </value>
            <value>
                <fullName>15 weeks</fullName>
            </value>
            <value>
                <fullName>16 weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Schedule_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Return_Date__c</fullName>
    <label>Schedule Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <label>Affiliate Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Inventory_Tool__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Tool__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Order Tool</relationshipLabel>
    <relationshipName>Order_Tools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp;OrderId,  Order.Name, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Requested_Borrowing_Period__c.field-meta.xml
<CustomField>
    <fullName>Requested_Borrowing_Period__c</fullName>
    <label>Requested Borrowing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 week</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
            </value>
            <value>
                <fullName>3 weeks</fullName>
            </value>
            <value>
                <fullName>4 weeks</fullName>
            </value>
            <value>
                <fullName>5 weeks</fullName>
            </value>
            <value>
                <fullName>6 weeks</fullName>
            </value>
            <value>
                <fullName>7 weeks</fullName>
            </value>
            <value>
                <fullName>8 weeks</fullName>
            </value>
            <value>
                <fullName>9 weeks</fullName>
            </value>
            <value>
                <fullName>10 weeks</fullName>
            </value>
            <value>
                <fullName>11 weeks</fullName>
            </value>
            <value>
                <fullName>12 weeks</fullName>
            </value>
            <value>
                <fullName>13 weeks</fullName>
            </value>
            <value>
                <fullName>14 weeks</fullName>
            </value>
            <value>
                <fullName>15 weeks</fullName>
            </value>
            <value>
                <fullName>16 weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Reserved_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Reserved_Quantity__c</fullName>
    <label>Confirmed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Schedule_Pick_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Pick_Date__c</fullName>
    <label>Schedule Pick Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Schedule_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Return_Date__c</fullName>
    <label>Schedule Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unconfirmed</fullName>
                <default>true</default>
                <label>Unconfirmed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Partially Returned</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>OverDue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
                <isActive>false</isActive>
                <label>Damaged</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Partially confirmed</fullName>
                <isActive>false</isActive>
                <label>Partially confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payments_TB__c/Payments_TB__c.object-meta.xml
<CustomObject>
    <label>Payment by Member</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payments_TB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments by Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payments_TB__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payments_TB__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments by Members</relationshipLabel>
    <relationshipName>Payments_by_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tool</fullName>
            </value>
            <value>
                <fullName>Additional Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory {
    
    public static Account createAccount(String name, String recordTypeid){
        Account acc = new Account(Name=name,recordTypeid=recordTypeid);
        insert acc;
        
        return acc;
    }
    
    public static contact createContact(String accId){
        contact con = new Contact();
        con.firstName = 'test';
        con.lastName = 'test';
        con.email = 'test@test.com';
        con.accountId = accId;
        insert con;
        
        return con;
    }
    
    public static Product2 createProduct(String Type){
        Product2 prod = new Product2();
        prod.name='test';
        prod.IsActive = true;
        prod.Type__c = Type;
        
        insert prod;
        
        return prod;
    }
    
    
    
    public static PricebookEntry createPricebookEntry(String prodId){
        
        PricebookEntry pbe = new PricebookEntry();
        pbe.product2Id = prodId;
        pbe.pricebook2Id = Test.getstandardPricebookId();
        pbe.unitPrice = 10;
        
        insert pbe;
        
        return pbe;
    }
    
    public static Order createOrder(String accId, String conId, string affiliate){
        Order ord = new Order();
        ord.accountId = accId;
        ord.name='test';
        ord.Affiliate__c = affiliate;
        ord.BillToContactId = conId;
        ord.Status='Unconfirmed';
        ord.pricebook2Id = Test.getstandardPricebookId();
        ord.effectiveDate = Date.today();
        ord.Schedule_return_date__c = Date.today().addDays(7);
        ord.Desired_pickup_date__c = Date.today();
        ord.EndDate = Date.today().addDays(7);
        ord.Requested_Borrowing_Period__c = '1 week';
        insert ord;
        
        return ord;
    }
    
    public static OrderItem createOrderItem(String orderId, String pbeId,String assetid){
        OrderItem ordItem = new OrderItem();
        ordItem.orderId = orderId;
        ordItem.PricebookEntryId =pbeId;
        ordItem.Inventory_Tool__c = assetid;
        ordItem.unitPrice = 10;
        ordItem.Affiliate_Handling_Fee__c = 3;
        ordItem.status__c = 'Unconfirmed';
        ordItem.Quantity = 5;
        ordItem.reserved_quantity__c = 5;
        ordItem.Schedule_Pick_Date__c = Date.today();
        ordItem.Schedule_return_date__c = Date.today().addDays(7);
        insert ordItem;
        LowestQuantityCalculateClasss.lowestQuantityOrder2(new List<order>{new order(Id=orderId)});
        return ordItem;
    }
    
    public static Credit__c createCredit(String accId, Date ExpiredDate){
        Credit__c credit = new Credit__c();
        credit.Expiration_Date__c = ExpiredDate;
        credit.Organization__c = accId;
        credit.Amount__c = 100;
        credit.isActive__c = true;
        insert credit;
        
        return credit;
    }
    
    public static Payments_TB__c createpayment(Order ord){
        Payments_TB__c payment = new Payments_TB__c();
        payment.order__c = ord.id;
        payment.Payment_Method__c = 'Organizational Credit';
        payment.Amount__c = 10;
        insert payment;
        return payment;
    }
    
    //@future
    public static User createCustomerUser(contact con, profile prof) {
        UserRole r = new UserRole(DeveloperName = 'MyCustomRole', Name = 'My Role');
        //insert r;
        User user1 = new User(
            Username = 'test12345@test.com',
            ContactId = con.Id,
            ProfileId = prof.Id,
            Alias = 'test123',
            Email = 'test12345@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'McTesty',
            CommunityNickname = 'test12345',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US'
            //UserRoleId = r.Id
        );
        insert user1;
        return user1;
    }
    
    public static Affiliate_Account__c createAffiliateAccount(Id accId) {
        Affiliate_Account__c affAcc = new Affiliate_Account__c(Affiliate__c = accId);
        insert affAcc;
        return affAcc;
    }
    public static Zip_Code__c createZipCode(String zip) {
        Zip_Code__c zipCode = new Zip_Code__c(Name = zip, Zip_Code__c = zip);
        insert zipCode;
        return zipCode;
    }
    public static Transaction__c createTransaction(Id assestId, Id recType, String subType) {
        Transaction__c tran = new Transaction__c(Inventory__c = assestId, Sub_Type__c = subType, Quantity__c = 5, RecordtypeId = recType);
        insert tran;
        return tran;
    }
}