force-app/main/default/objects/Account/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Affiliate Handling Fee</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Requested_Borrowing_Period__c.field-meta.xml
<CustomField>
    <fullName>Requested_Borrowing_Period__c</fullName>
    <label>Requested Borrowing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 week</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
            </value>
            <value>
                <fullName>3 weeks</fullName>
            </value>
            <value>
                <fullName>4 weeks</fullName>
            </value>
            <value>
                <fullName>5 weeks</fullName>
            </value>
            <value>
                <fullName>6 weeks</fullName>
            </value>
            <value>
                <fullName>7 weeks</fullName>
            </value>
            <value>
                <fullName>8 weeks</fullName>
            </value>
            <value>
                <fullName>9 weeks</fullName>
            </value>
            <value>
                <fullName>10 weeks</fullName>
            </value>
            <value>
                <fullName>11 weeks</fullName>
            </value>
            <value>
                <fullName>12 weeks</fullName>
            </value>
            <value>
                <fullName>13 weeks</fullName>
            </value>
            <value>
                <fullName>14 weeks</fullName>
            </value>
            <value>
                <fullName>15 weeks</fullName>
            </value>
            <value>
                <fullName>16 weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <label>Affiliate Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Lost__c.field-meta.xml
<CustomField>
    <fullName>Lost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lost</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Requested_Borrowing_Period__c.field-meta.xml
<CustomField>
    <fullName>Requested_Borrowing_Period__c</fullName>
    <label>Requested Borrowing Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 week</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
            </value>
            <value>
                <fullName>3 weeks</fullName>
            </value>
            <value>
                <fullName>4 weeks</fullName>
            </value>
            <value>
                <fullName>5 weeks</fullName>
            </value>
            <value>
                <fullName>6 weeks</fullName>
            </value>
            <value>
                <fullName>7 weeks</fullName>
            </value>
            <value>
                <fullName>8 weeks</fullName>
            </value>
            <value>
                <fullName>9 weeks</fullName>
            </value>
            <value>
                <fullName>10 weeks</fullName>
            </value>
            <value>
                <fullName>11 weeks</fullName>
            </value>
            <value>
                <fullName>12 weeks</fullName>
            </value>
            <value>
                <fullName>13 weeks</fullName>
            </value>
            <value>
                <fullName>14 weeks</fullName>
            </value>
            <value>
                <fullName>15 weeks</fullName>
            </value>
            <value>
                <fullName>16 weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unconfirmed</fullName>
                <default>true</default>
                <label>Unconfirmed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Partially Returned</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>OverDue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
                <isActive>false</isActive>
                <label>Damaged</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Partially confirmed</fullName>
                <isActive>false</isActive>
                <label>Partially confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreatePaymentControllerTest.cls
@isTest
public class CreatePaymentControllerTest {
   
    @isTest
    static void unitTest1(){
        Account acc = new Account();
        acc.name = 'Test';
        
        insert acc;
        
        order order = new order();
		order.accountid = acc.id;
        order.Name = 'Test';
        order.pricebook2Id = Test.getstandardPricebookId();
        order.EffectiveDate = Date.today(); 
        order.Status = 'Unconfirmed';
        insert order;
        product2 product = TestDataFactory.createProduct('Additional Charges');
        PricebookEntry PricebookEntry = TestDataFactory.createPricebookEntry(product.id);
        
        OrderItem ordItem = new OrderItem();
        ordItem.orderId = order.Id;
        ordItem.PricebookEntryId =PricebookEntry.Id;
        ordItem.unitPrice = 10;
        ordItem.Affiliate_Handling_Fee__c = 0.03;
        ordItem.status__c = 'Unconfirmed';
        ordItem.Quantity = 1;
        ordItem.Lost__c = 1;
        ordItem.Requested_Borrowing_Period__c = '1 week';
        insert ordItem;
        
        CreatePaymentController.getOrderDetails(order.Id);
        CreatePaymentController.refreshOrderDetails(order.Id);
        String payment = '{'
                           +'     "comments":"comments",'
                           +'     "amount":"1",'
                           +'     "method":"Credit Card",'
                           +'     "orderId":"'+order.Id
                           +'"}';
        CreatePaymentController.createPayment(payment);
        
    }
}