force-app/main/default/objects/Account/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Affiliate Handling Fee</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Flagged__c.field-meta.xml
<CustomField>
    <fullName>Flagged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flagged?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Affiliate_Account__c/Affiliate_Account__c.object-meta.xml
<CustomObject>
    <label>Affiliate Account</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Affiliate Account No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliate Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Account__c/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <label>Affiliate</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliate Users</relationshipLabel>
    <relationshipName>Affiliate_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Affiliate_Account__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Affiliate_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <formula>Account.Affiliate_Handling_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Affiliate Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Spanish_Name__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Name__c</fullName>
    <formula>Product2.Spanish_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Spanish Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <formula>TEXT(Product2.Sub_Category__c )</formula>
    <label>Sub-Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Unlisted_Item__c.field-meta.xml
<CustomField>
    <fullName>Unlisted_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unlisted Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <description>The affiliate to which the contact is most closely connected.</description>
    <inlineHelpText>Select the affiliate to which the contact is most closely connected.  Go to www.toolbank.org/citycodes to view a city code list.</inlineHelpText>
    <label>Affiliate</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ATL</fullName>
            </value>
            <value>
                <fullName>BLT</fullName>
            </value>
            <value>
                <fullName>CHI</fullName>
            </value>
            <value>
                <fullName>CIN</fullName>
            </value>
            <value>
                <fullName>CLT</fullName>
            </value>
            <value>
                <fullName>DEN</fullName>
            </value>
            <value>
                <fullName>DET</fullName>
            </value>
            <value>
                <fullName>HFD</fullName>
            </value>
            <value>
                <fullName>HOU</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NWK</fullName>
            </value>
            <value>
                <fullName>PDX</fullName>
            </value>
            <value>
                <fullName>PHX</fullName>
            </value>
            <value>
                <fullName>RVA</fullName>
            </value>
            <value>
                <fullName>SAT</fullName>
            </value>
            <value>
                <fullName>SAV</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
                <default>true</default>
                <label>USA</label>
            </value>
            <value>
                <fullName>WDC</fullName>
            </value>
            <value>
                <fullName>WNS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliate</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliate Orders</relationshipLabel>
    <relationshipName>AffiliateOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Areas_Of_Impact__c.field-meta.xml
<CustomField>
    <fullName>Areas_Of_Impact__c</fullName>
    <label>Areas Of Impact</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Animal Welfare</fullName>
            </value>
            <value>
                <fullName>Arts, Culture, Humanities</fullName>
            </value>
            <value>
                <fullName>Community Revitalization</fullName>
            </value>
            <value>
                <fullName>Disaster Relief and Recovery</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Environment and Greenspace</fullName>
            </value>
            <value>
                <fullName>Faith Based</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing and Homelessness</fullName>
            </value>
            <value>
                <fullName>Human Services</fullName>
            </value>
            <value>
                <fullName>Veteran Services</fullName>
            </value>
            <value>
                <fullName>Youth and Children</fullName>
            </value>
            <value>
                <fullName>Public Societal Benefit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Desired_Pickup_Date__c.field-meta.xml
<CustomField>
    <fullName>Desired_Pickup_Date__c</fullName>
    <label>Desired Pickup Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Community / Neighborhood Cleanup</fullName>
            </value>
            <value>
                <fullName>Demolition/Clearing</fullName>
            </value>
            <value>
                <fullName>Disaster Recovery/Response</fullName>
            </value>
            <value>
                <fullName>Environment Conservation</fullName>
            </value>
            <value>
                <fullName>Landscaping/Beautification</fullName>
            </value>
            <value>
                <fullName>Planting/Groundskeeping</fullName>
            </value>
            <value>
                <fullName>Repairs/Maintenance/Renovation/Additions</fullName>
            </value>
            <value>
                <fullName>Special Events/Fundraisers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Project_Venue__c.field-meta.xml
<CustomField>
    <fullName>Project_Venue__c</fullName>
    <label>Project Venue</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency Facility</fullName>
            </value>
            <value>
                <fullName>Public Space or Venue</fullName>
            </value>
            <value>
                <fullName>Residence or Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Serving_50_of_Low_Income_People__c.field-meta.xml
<CustomField>
    <fullName>Serving_50_of_Low_Income_People__c</fullName>
    <label>Serving &lt; 50% of Low Income People</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Project(s) are being completed in an area considered to be low-income.</fullName>
            </value>
            <value>
                <fullName>All Project(s) are being completed in an area(s) considered to be low-income to moderate-income.</fullName>
            </value>
            <value>
                <fullName>None of the above.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Zip_Code__c/Order_Zip_Code__c.object-meta.xml
<CustomObject>
    <label>Order Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Zip Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Zip_Code__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <referenceTo>Zip_Code__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <label>Affiliate Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Highlights__c.field-meta.xml
<CustomField>
    <fullName>Highlights__c</fullName>
    <label>Highlights</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Common Tool</fullName>
            </value>
            <value>
                <fullName>New Tool</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Job_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Image__c.field-meta.xml
<CustomField>
    <fullName>Product_Image__c</fullName>
    <label>Product Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sort_Category__c.field-meta.xml
<CustomField>
    <fullName>Sort_Category__c</fullName>
    <label>Sort Category</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Spanish_Name__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Name__c</fullName>
    <label>Spanish Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Tool_Note__c.field-meta.xml
<CustomField>
    <fullName>Tool_Note__c</fullName>
    <label>Tool Note</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tool</fullName>
            </value>
            <value>
                <fullName>Additional Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code__c/fields/zip_Code__c.field-meta.xml
<CustomField>
    <fullName>zip_Code__c</fullName>
    <externalId>true</externalId>
    <label>zip Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Job_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Assembling</fullName>
    </customValue>
    <customValue>
        <fullName>Cement</fullName>
    </customValue>
    <customValue>
        <fullName>Demolition</fullName>
    </customValue>
    <customValue>
        <fullName>Ditching/Digging</fullName>
    </customValue>
    <customValue>
        <fullName>Festivals and Races</fullName>
    </customValue>
    <customValue>
        <fullName>Framing</fullName>
    </customValue>
    <customValue>
        <fullName>Gatherings</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Cleanup</fullName>
    </customValue>
    <customValue>
        <fullName>Painting</fullName>
    </customValue>
    <customValue>
        <fullName>Planting/Beautification</fullName>
    </customValue>
    <customValue>
        <fullName>Playground build</fullName>
    </customValue>
    <customValue>
        <fullName>Sheetrock/Drywall</fullName>
    </customValue>
    <masterLabel>Job Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sub_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A-frame</fullName>
    </customValue>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Augers</fullName>
    </customValue>
    <customValue>
        <fullName>Batteries</fullName>
    </customValue>
    <customValue>
        <fullName>Blowers</fullName>
    </customValue>
    <customValue>
        <fullName>Brush clearing/chainsaws</fullName>
    </customValue>
    <customValue>
        <fullName>Buckets</fullName>
    </customValue>
    <customValue>
        <fullName>Carts</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaning</fullName>
    </customValue>
    <customValue>
        <fullName>Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Cutting</fullName>
    </customValue>
    <customValue>
        <fullName>Decorations &amp; Lighting</fullName>
    </customValue>
    <customValue>
        <fullName>Demolition</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Digging</fullName>
    </customValue>
    <customValue>
        <fullName>Dolly/Hand Trucks</fullName>
    </customValue>
    <customValue>
        <fullName>Drills</fullName>
    </customValue>
    <customValue>
        <fullName>Drywall &amp; Masonry</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Fans &amp; Heaters</fullName>
    </customValue>
    <customValue>
        <fullName>Food &amp; Beverage</fullName>
    </customValue>
    <customValue>
        <fullName>Forks</fullName>
    </customValue>
    <customValue>
        <fullName>Games &amp; Recreation</fullName>
    </customValue>
    <customValue>
        <fullName>Generators</fullName>
    </customValue>
    <customValue>
        <fullName>Gloves</fullName>
    </customValue>
    <customValue>
        <fullName>Hammers &amp; Chisels</fullName>
    </customValue>
    <customValue>
        <fullName>Hoses</fullName>
    </customValue>
    <customValue>
        <fullName>Invasive removal</fullName>
    </customValue>
    <customValue>
        <fullName>Jacks</fullName>
    </customValue>
    <masterLabel>Sub-Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PlaceOrderController.cls
public without Sharing class PlaceOrderController {
    
    @AuraEnabled(cacheable = true)
    public static Boolean getFlag(){
        Boolean flagged = [SELECT Id, Contact.Account.parentId, Contact.Account.Flagged__c FROM User WHERE Id =: UserInfo.getUserId()].Contact.Account.Flagged__c;
        
        return flagged;
    }
    
    @AuraEnabled(cacheable = true)
    public static string accid(){
        String accid = [SELECT Id, Contact.Account.parentId FROM User WHERE Id =: UserInfo.getUserId()].Contact.Account.parentId;
        if(String.isBlank(accId)){
            List<Affiliate_Account__c> aff = [SELECT Id, Affiliate__c,Affiliate__r.Name FROM Affiliate_Account__c WHERE User__c =:UserInfo.getUserId()];
            if(aff != null && aff.size() >0 && aff.size() == 1)
                accid = aff[0].Affiliate__c;
        }
        return accId;
    }
    
    @AuraEnabled(cacheable = true)
    public static User getAgencyContact(){
        User user = [SELECT Id,contactId, Contact.Email, Contact.AccountId,Contact.Name,contact.Account.Name FROM User WHERE Id =: UserInfo.getUserId()];
        
        return user;
    }
    
    @AuraEnabled(cacheable = true)
    public static List<Account> getAffiliate(){
        List<Account> accList = new List<Account>();
        for(Affiliate_Account__c aff: [SELECT Id, Affiliate__c,Affiliate__r.Name FROM Affiliate_Account__c WHERE User__c =:UserInfo.getUserId()]){
            accList.add(aff.Affiliate__r);
        }
        
        if(accList != Null && accList.size() >0)
            return accList;
        else return  [SELECT Id,Name FROM Account WHERE RecordTypeId='012020000000KwbAAE'];
    }
    
    @AuraEnabled(cacheable = true)
    public static List<Tool> returnAssets(String searchString,String affiliateId){
        try {
            String accid = [SELECT Id, Contact.Account.parentId FROM User WHERE Id =: UserInfo.getUserId()].Contact.Account.parentId;
            List<Asset> assetList;
            List<Tool> tools = new List<Tool>();
            if(String.isNotBlank(affiliateId)){
                accId = affiliateId;
            }
            if(String.isBlank(searchString)){
                assetList=  [SELECT Id,
                             Affiliate_Handling_Fee__c,
                             Product2Id,
                             Product2.spanish_name__c,
                             Product2.Job_Type__c,
                             Product2.Highlights__c,
                             Product2.Name,
                             Product2.productCode,
                             Product2.Sub_Category__c,
                             Product2.Family,
                             Product2.Product_Image__c,
                             Product2.Tool_Note__c,
                             price 
                             FROM Asset
                             WHERE AccountId =: accid
                             AND Unlisted_Item__c = false
                             AND Product2.type__c = 'Tool'
                             AND (Quantity != Null 
                                  AND Quantity != 0)];
                
            }else {
                searchString = '%'+searchString+'%';
                assetList=  [SELECT Id,Affiliate_Handling_Fee__c,
                             Product2Id,
                             Product2.spanish_name__c,
                             Product2.Job_Type__c,
                             Product2.Highlights__c,
                             Product2.Name,
                             Product2.productCode,
                             Product2.Sub_Category__c,
                             Product2.Family,
                             Product2.Product_Image__c,
                             Product2.Tool_Note__c,
                             price 
                             FROM Asset 
                             WHERE AccountId =: accid 
                             AND Unlisted_Item__c = false
                             AND (Product2.Name like: searchString 
                                  OR Product2.spanish_name__c like: searchString
                                  OR Product2.Family like: searchString 
                                  OR Product2.sub_category__c like: searchString 
                                  OR Product2.productCode like: searchString 
                                  OR Product2.Tool_Note__c like: searchString )
                             AND Product2.type__c = 'Tool'
                             AND (Quantity != Null 
                                  AND Quantity != 0)];
                
            }
            Map<Id, Asset> productIdAssetMap = new Map<Id, Asset>();
            for(Asset asset: assetList){
                productIdAssetMap.put(asset.Product2Id, asset);
            }
            
            for(PriceBookEntry pbe: [SELECT Id,Product2.spanish_name__c,product2Id,unitPrice 
                                     FROM PriceBookEntry 
                                     WHERE Product2Id IN: productIdAssetMap.keyset() 
                                     AND Product2.type__c = 'Tool'
                                     ORDER BY product2.Sort_Category__c,product2.Family, product2.sub_category__c]){
                                         Tool tool = new Tool();
                                         tool.asset = productIdAssetMap.get(pbe.product2Id);
                                         tool.pbe = pbe;
                                         tool.hanlingFee = (pbe.unitPrice*tool.asset.Affiliate_Handling_Fee__c/100).setScale(2);
                                         
                                         tools.add(tool);
                                     }
            
            return tools;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> zipCodes(){
        try {
            List<String> zipcodes = new List<String>();
            for(Zip_Code__c zip : [SELECT name FROM Zip_Code__c]){
                zipcodes.add(zip.name);
            }
            return zipcodes;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static string placeOrder(String Order){
        Map<String,object> orderDetail = (map<string,object>)JSON.deserializeUntyped(order);
        Map<String,object> orderObj = (Map<String,object>)orderDetail.get('order');
        List<Object> toolObj = (List<Object>)orderDetail.get('tools');
        
        Order ord = new Order();
        ord.status = 'Unconfirmed';
        ord.pricebook2Id = '01sA0000000PfKSIA0';
        ord.name = (String)orderObj.get('name');
        String zipCodes = (String)orderObj.get('zip');
        ord.Serving_50_of_Low_Income_People__c = (String)orderObj.get('serv');
        List<Object> proVenueList = (List<Object>)orderObj.get('proVenue');
        List<Object> proTypeList = (List<Object>)orderObj.get('proType');
        List<Object> impactAreaList = (List<Object>)orderObj.get('impactArea');
        String proVenue='';
        for(Object obj: proVenueList){
            proVenue += (String)obj+';';
        }
        String proType='';
        for(Object obj: proTypeList){
            proType += (String)obj+';';
        }
        String impactArea='';
        for(Object obj: impactAreaList){
            impactArea += (String)obj+';';
        }
        ord.Project_Venue__c = proVenue;
        ord.Project_Type__c = proType;
        ord.Areas_Of_Impact__c = impactArea;
        ord.AccountId = (String)orderObj.get('accountId');
        ord.BillToContactId = (String)orderObj.get('contactId');
        ord.Desired_Pickup_Date__c = Date.valueOf((String)orderObj.get('pickdate'));
        ord.Desired_Pickup_Time__c = (String)orderObj.get('pickTime');
        ord.EndDate = Date.valueOf((String)orderObj.get('retDate'));
        ord.Requested_Borrowing_Period__c = (String)orderObj.get('duration');
        ord.Corporation_Name__c = (String)orderObj.get('corpname');
        if((String)orderObj.get('home') != null)
            ord.If_Yes_How_Many_Homes__c = Decimal.valueOf((String)orderObj.get('home'));
        ord.EffectiveDate =ord.Desired_Pickup_Date__c;
        ord.Affiliate__c = (String)orderObj.get('affiliateid');
        String peopleserved= (String)orderObj.get('peopledirectlyserved');
        String projectNumber= (String)orderObj.get('numberProject');
        String avgHr= (String)orderObj.get('onsitehours');
        String voluNumber= (String)orderObj.get('volunteersnumber');
        String staff= (String)orderObj.get('staff');
        String totalVol= (String)orderObj.get('projectVolunteerHr');
        String peopleimpact= (String)orderObj.get('peopleImImpacted');
        ord.Volunteer_Source__c = (String)orderObj.get('volunteersource');
        
        ord.People_Directly_Served__c = String.isBlank(peopleserved)?null: Decimal.valueOf(peopleserved);
        ord.Number_Of_Projects__c = String.isBlank(projectNumber)?null: Decimal.valueOf(projectNumber);
        ord.Hours_Average_Volunteer_is_on_Site__c = String.isBlank(avgHr)?null: Decimal.valueOf(avgHr);
        ord.Number_of_Volunteers__c = String.isBlank(voluNumber)?null: Decimal.valueOf(voluNumber);
        ord.People_Indirectly_Impacted__c = String.isBlank(peopleimpact)?null: Decimal.valueOf(peopleimpact);
        ord.Staff_on_this_Project__c = String.isBlank(staff)?null: Decimal.valueOf(staff);
        ord.Total_Project_Volunteer_Hours__c = String.isBlank(totalVol)?null: Decimal.valueOf(totalVol);
        insert ord;
        
        if(zipCodes != null){
            list<String> zipCodeList =  zipCodes.split(',');
            if(zipCodeList != null && zipCodeList.size() >0){
                list<Order_Zip_Code__c> ordZipCodes = new List<Order_Zip_Code__c>();
                for(String zip: zipCodeList){
                    system.debug(zip);
                    if(!String.isblank(zip)){
                        Order_Zip_Code__c ordZip = new Order_Zip_Code__c();
                        ordZip.Order__c = ord.id;
                        ordZip.name = zip;
                        ordZip.Zip_Code__r = new Zip_Code__c(Zip_Code__c = zip);
                        ordZipCodes.add(ordZip); 
                    }
                }
                
                if(!ordZipCodes.isEmpty())
                    insert ordZipCodes;
            }
        }
        
        List<OrderItem> orderItemList = new List<OrderItem>();
        for(Object tool:toolObj){
            Map<String, Object> product = ( Map<String, Object>)tool;
            OrderItem item = new OrderItem();
            item.quantity = Decimal.valueOf((String)product.get('quantity'));
            item.unitPrice = Decimal.valueOf((String)product.get('retailPrice'));
            item.Affiliate_Handling_Fee__c = Decimal.valueOf((String)product.get('affiliatefee'));
            item.Requested_Borrowing_Period__c = (String)orderObj.get('duration');
            item.PriceBookEntryId = (String)product.get('pbeid');
            item.Inventory_Tool__c = (String)product.get('assetId');
            item.orderId = ord.id;
            item.Schedule_Pick_Date__c = Date.valueOf((String)orderObj.get('pickdate'));
            item.Schedule_Return_Date__c = Date.valueOf((String)orderObj.get('retDate'));
            item.status__c= 'Unconfirmed';
            orderItemList.add(item);
        }
        
        
        
        if(!orderItemList.isEmpty())
            insert orderItemList;
        
        if(ord != Null)
            LowestQuantityCalculateClasss.lowestQuantityOrder2(new List<order>{ord});
        
        return '/'+ord.id;
    }
    
    public class Tool{
        @AuraEnabled
        public Asset asset;
        @AuraEnabled
        public PriceBookEntry pbe;
        @AuraEnabled
        public Decimal hanlingFee;
    }
    
}