force-app/main/default/objects/Account/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Affiliate Handling Fee</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Affiliate.recordType-meta.xml
<RecordType>
    <fullName>Affiliate</fullName>
    <active>true</active>
    <description>Affiliate Account</description>
    <label>Affiliate</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Affiliate_Handling_Fee__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Handling_Fee__c</fullName>
    <formula>Account.Affiliate_Handling_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Affiliate Handling Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Txn-{00000000}</displayFormat>
        <label>Transaction No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Worn - Out</fullName>
            </value>
            <value>
                <fullName>No Longer Carry</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Gift Card</fullName>
            </value>
            <value>
                <fullName>Restricted Funds</fullName>
            </value>
            <value>
                <fullName>General Funds</fullName>
            </value>
            <value>
                <fullName>Corporate Donation</fullName>
            </value>
            <value>
                <fullName>Individual Donation</fullName>
            </value>
            <value>
                <fullName>Member Agency Donation</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Rebranding</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Destroyed</fullName>
            </value>
            <value>
                <fullName>Increase</fullName>
            </value>
            <value>
                <fullName>Decrease</fullName>
            </value>
            <value>
                <fullName>Lost - Return</fullName>
            </value>
            <value>
                <fullName>Lost from Inventory</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
                <isActive>false</isActive>
                <label>Allocated</label>
            </value>
            <value>
                <fullName>Donated</fullName>
                <isActive>false</isActive>
                <label>Donated</label>
            </value>
            <value>
                <fullName>Donation</fullName>
                <isActive>false</isActive>
                <label>Donation</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Purchased</fullName>
                <isActive>false</isActive>
                <label>Purchased</label>
            </value>
            <value>
                <fullName>Return</fullName>
                <isActive>false</isActive>
                <label>Return</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/Transfer.recordType-meta.xml
<RecordType>
    <fullName>Transfer</fullName>
    <active>true</active>
    <label>Transfer</label>
</RecordType>

force-app/main/default/classes/CreateTransactionTest.cls
@isTest
public class CreateTransactionTest implements HttpCalloutMock {
    
    @isTest
    static void createTransactionTest(){
     
        String recordTypeid  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Member Agency').getRecordTypeId();
        Account acc = TestDataFactory.createAccount('test',recordTypeid);
        String recordTypeid2  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Affiliate').getRecordTypeId();
        
        contact con = TestDataFactory.createContact(acc.Id);
        Product2 tool = TestDataFactory.createProduct('Tool');
        Product2 tool2 = TestDataFactory.createProduct('Tool');
        PricebookEntry toolpbe = TestDataFactory.createPricebookEntry(tool.Id);
        PricebookEntry toolpbe2 = TestDataFactory.createPricebookEntry(tool2.Id);
        Account affiliate1 = TestDataFactory.createAccount('test1',recordTypeid2);
        Account affiliate2 = TestDataFactory.createAccount('test2',recordTypeid2);
        acc.parentId = affiliate2.Id;
        update acc;
        affiliate2.Affiliate_Handling_Fee__c = 3;
        update affiliate2;
        Asset ast = new Asset(Name = 'test', Product2Id = tool.Id, AccountId = affiliate1.Id, Quantity = 10);
        insert ast;
        //List<Asset> asset = [Select Id FROM Asset];

        List<CreateTransaction.PickListOption> recordTypeOptionList = CreateTransaction.getRecordType();
        String recordTypeid3  = Schema.SObjectType.Transaction__c.getRecordTypeInfosByName().get('Transfer').getRecordTypeId();
        String recordTypeid4  = Schema.SObjectType.Transaction__c.getRecordTypeInfosByName().get('Inventory Audit').getRecordTypeId();
        Test.setMock(HttpCalloutMock.class, new CreateTransactionTest());
        Test.startTest();
        CreateTransaction.getValues('Transaction__C', recordTypeid3, 'Sub_type__c');
        CreateTransaction.CreateTransaction(ast.Id, recordTypeid3, 'Decrease', 3, 'test',affiliate2.Id);
        CreateTransaction.CreateTransaction(ast.Id, recordTypeid4, 'Increase', 3, 'test',affiliate2.Id);
        Test.stopTest();
    }

    public HTTPResponse respond(HTTPRequest req) {
        
        HTTPResponse res = new HTTPResponse();
        res.setStatusCode(200);
        res.setStatus('OK');
        res.setbody(    '{"values":[{'
                        +'"label":"Maintenance",'
                        +'"value": "Maintenance"'
                        +'},'
                        +'{'
                        +'"label": "Rebranding",'
                        +'"value": "Rebranding"'
                        +'}]}');

        return res;

    }
}