force-app/main/default/objects/Account/fields/Affiliate_Email__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Email__c</fullName>
    <formula>Owner.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Affiliate Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Affiliate_Phone__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Phone__c</fullName>
    <formula>&quot;(&quot; &amp; LEFT(Parent.Phone, 3) &amp; &quot;) &quot; &amp; LEFT(RIGHT(Parent.Phone, 7), 3) &amp; &quot;-&quot; &amp; RIGHT(Parent.Phone, 4)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Affiliate Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agency_Impact__c.field-meta.xml
<CustomField>
    <fullName>Agency_Impact__c</fullName>
    <label>Agency Impact (low income)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Agency_Mission__c.field-meta.xml
<CustomField>
    <fullName>Agency_Mission__c</fullName>
    <label>Agency Mission</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arts, Culture, Humanities</fullName>
            </value>
            <value>
                <fullName>Community improvement</fullName>
            </value>
            <value>
                <fullName>Educational institution</fullName>
            </value>
            <value>
                <fullName>Environmental quality/protection</fullName>
            </value>
            <value>
                <fullName>Faith-based institution</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Human &amp; Community Services</fullName>
            </value>
            <value>
                <fullName>International/foreign affairs</fullName>
            </value>
            <value>
                <fullName>Low income housing provider</fullName>
            </value>
            <value>
                <fullName>Non-profit improvement</fullName>
            </value>
            <value>
                <fullName>Public/social benefits</fullName>
            </value>
            <value>
                <fullName>Social services</fullName>
            </value>
            <value>
                <fullName>Youth development</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Veterans services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Annual_Budget__c.field-meta.xml
<CustomField>
    <fullName>Annual_Budget__c</fullName>
    <label>Annual Budget</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Annual_Budget</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Facebook__c.field-meta.xml
<CustomField>
    <fullName>Facebook__c</fullName>
    <label>Facebook</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FT__c.field-meta.xml
<CustomField>
    <fullName>FT__c</fullName>
    <label>FT</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Instagram__c.field-meta.xml
<CustomField>
    <fullName>Instagram__c</fullName>
    <label>Instagram</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/npo02__MembershipEndDate__c.field-meta.xml
<CustomField>
    <fullName>npo02__MembershipEndDate__c</fullName>
    <description>Do not manually update. Updated by automatic processes. See Record Types in Household Settings.</description>
    <inlineHelpText>Membership end date from most recent (by Close Date) won Membership Opportunity (by Record Type) related to this Account.</inlineHelpText>
    <label>Membership End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/npo02__MembershipJoinDate__c.field-meta.xml
<CustomField>
    <fullName>npo02__MembershipJoinDate__c</fullName>
    <description>Do not manually update. Updated by automatic processes. See Record Types in Household Settings.</description>
    <inlineHelpText>Membership start date from most recent (by Close Date) won Membership Opportunity (by Record Type) related to this Account.</inlineHelpText>
    <label>Membership Join Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/PT__c.field-meta.xml
<CustomField>
    <fullName>PT__c</fullName>
    <label>PT</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Twitter__c.field-meta.xml
<CustomField>
    <fullName>Twitter__c</fullName>
    <label>Twitter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Warehouse_Manager__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Warehouse_Manager_Email__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Manager_Email__c</fullName>
    <formula>Warehouse_Manager__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse Manager Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Warehouse_Manager_Phone__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Manager_Phone__c</fullName>
    <formula>Warehouse_Manager__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse Manager Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Affiliate_Phone__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Phone__c</fullName>
    <formula>&quot;(&quot; &amp; LEFT(npsp__Primary_Affiliation__r.Parent.Phone, 3) &amp; &quot;) &quot; &amp; LEFT(RIGHT(npsp__Primary_Affiliation__r.Parent.Phone, 7), 3) &amp; &quot;-&quot; &amp; RIGHT(npsp__Primary_Affiliation__r.Parent.Phone, 4)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Affiliate Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Executive_Contact__c.field-meta.xml
<CustomField>
    <fullName>Executive_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this contact an executive at their organization?</inlineHelpText>
    <label>Executive Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Executive_Home_Phone__c.field-meta.xml
<CustomField>
    <fullName>Executive_Home_Phone__c</fullName>
    <label>Phone 1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npo02__MembershipEndDate__c.field-meta.xml
<CustomField>
    <fullName>npo02__MembershipEndDate__c</fullName>
    <description>Do not change. Updated by automatic processes.</description>
    <inlineHelpText>The Membership End Date of the most recent (Close Date) Membership Opportunity (Record Type) related to this Contact by primary Opportunity Contact Role.</inlineHelpText>
    <label>Membership End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npo02__MembershipJoinDate__c.field-meta.xml
<CustomField>
    <fullName>npo02__MembershipJoinDate__c</fullName>
    <description>Do not change. Updated by automatic processes.</description>
    <inlineHelpText>The Join Date of the oldest (Close Date) Membership Opportunity (Record Type) related to this Contact by primary Opportunity Contact Role.</inlineHelpText>
    <label>Membership Join Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account marked as Primary in this Contact&apos;s list of Organization Affiliations.</description>
    <inlineHelpText>The Account marked as Primary in this Contact&apos;s list of Organization Affiliations.</inlineHelpText>
    <label>Primary Affiliation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Do Not Use.  Use Organization Affiliations.</relationshipLabel>
    <relationshipName>PrimaryAffiliatedContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(User__c ==null , &apos;User Not Created&apos; , IF(User__c !=null &amp;&amp; User__r.IsActive, &apos;Active&apos;, &apos;Inactive&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Unsubscribe_Notifications__c.field-meta.xml
<CustomField>
    <fullName>Unsubscribe_Notifications__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Turn Off Notifications</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Affiliate_Phone__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Phone__c</fullName>
    <formula>&quot;(&quot; &amp; LEFT(Contact.npsp__Primary_Affiliation__r.Parent.Phone, 3) &amp; &quot;) &quot; &amp; LEFT(RIGHT(Contact.npsp__Primary_Affiliation__r.Parent.Phone, 7), 3) &amp; &quot;-&quot; &amp; RIGHT(Contact.npsp__Primary_Affiliation__r.Parent.Phone, 4)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Affiliate Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Annual_Budget.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>$0 - $100,000</fullName>
    </customValue>
    <customValue>
        <fullName>$100,001 - $250,000</fullName>
    </customValue>
    <customValue>
        <fullName>$250,001 - $500,000</fullName>
    </customValue>
    <customValue>
        <fullName>$500,001 - $750,000</fullName>
    </customValue>
    <customValue>
        <fullName>$750,001 - and above</fullName>
    </customValue>
    <customValue>
        <fullName>*Public School System</fullName>
    </customValue>
    <customValue>
        <fullName>*All Government Agencies</fullName>
    </customValue>
    <masterLabel>Annual Budget</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/show_AccountsinCommunityCtrl.cls
public without Sharing class show_AccountsinCommunityCtrl {
    public string name {get;set;}
    public String Phone {get;set;}
    public string Billingaddress{get;set;}
    public String BillingStreet {get;set;}
    public string BillingCity{get;set;}
    public String BillingState{get;set;}
    public string BillingCountry{get;set;}
    public String BillingPostalCode {get;set;}
    public String website{get; set;}
    public String annualbudget{get; set;}
    public String agencyImpact {get;set;}
    public String agencyMission {get;set;}
    public String staffFT {get;set;}
    public String staffPT {get;set;}
    public String insta {get;set;}
    public String face {get;set;}
    public String tweet {get;set;}
    public List<string> ids{get;set;}
    public String conEdit{get;set;}
    public String memberexpDate{get; set;}
    public String memberStatus{get;set;}
    public String memberstartDate{get;set;}
    public contact getcont{get;set;}
    Public Account accDetails {Set;Get;}
    public boolean panel1{get;set;}
    public boolean panel2{get; set;}
    public boolean panel3{get; set;}
    public Contact getcontc {get; set;}
    public Boolean primaryId{get; set;}
    public Boolean ExecutivecontactId{get; set;}
    //public String accLoc{get;set;}
    public String conId{get;set;}
    public Boolean showAccount {get;set;}  
    public Boolean hideAccount {get;set;}
    public List<Contact> deleteContact {get;set;}
    public String accId{get;set;}
    public string affiliateContact {get;set;}
    public string affiliateEmail {get;set;}
    public string affiliatePhone {get;set;}
    public string warehouseManager {get;set;}
    public string warehouseManagerEmail {get;set;}
    public string warehouseManagerPhone {get;set;}
    
    public show_AccountsinCommunityCtrl(){
        size=3;
        ids = new List<String>();
        showAccount= true;
        hideAccount = false;
        deleteContact = new List<Contact>();    
        getcont = new contact();
        getcontc = new contact();
        contact con  = [Select contactId,contact.AccountId, contact.npsp__Primary_Affiliation__c,Contact.Primary_contact__c,Contact.Executive_Contact__c from user where id=:userinfo.getuserid()].Contact;
        conId = con.Id;
        primaryId = con.Primary_contact__c;
        System.debug(PrimaryId);
        ExecutivecontactId = con.Executive_Contact__c;
        System.debug(ExecutivecontactId);
        System.debug(conId );
        if(con.npsp__Primary_Affiliation__c != Null)
        accId = con.npsp__Primary_Affiliation__c;
        else accId = con.AccountId;
        accDetails  =   [Select id,Name,Affiliate_Email__c,Affiliate_Phone__c,owner.name, 
                        Warehouse_Manager__c,Warehouse_Manager__r.name, 
                        Warehouse_Manager_Email__c,Warehouse_Manager_Phone__c,
                        Phone,Billingaddress,BillingStreet,BillingCity,BillingState,
                        BillingCountry,BillingPostalCode,website,annual_budget__c,
                        npo02__MembershipEndDate__c,npo02__MembershipJoinDate__c,
                        Agency_Impact__c,Agency_Mission__c ,PT__c,FT__c,
                        Instagram__c,Facebook__c,twitter__c,Membership_Status__c
                        from Account 
                        where id=:accId ];
        System.debug('##'+accDetails);
        name = accDetails.Name;
        Phone =accDetails.Phone;
        
        BillingStreet=accDetails.BillingStreet;
        BillingCity= accDetails.BillingCity;
        BillingState=accDetails.BillingState;
        BillingCountry= accDetails.BillingCountry;
        BillingPostalCode =accDetails.BillingPostalCode ;
        website=accDetails.website;
        annualbudget=accDetails.annual_budget__c;
        memberexpDate=String.valueOf(accDetails.npo02__MembershipEndDate__c);
        memberStatus=accDetails.Membership_Status__c;
        memberstartDate=String.valueof(accDetails.npo02__MembershipJoinDate__c);
        ids.add(con.npsp__Primary_Affiliation__c);
        ids.add(con.AccountId);
        //accLoc=accDetails.Parent.Community_URL_Prefix__c;
        agencyImpact = accDetails.Agency_Impact__c;
        agencyMission=accDetails.Agency_Mission__c;
        if(accDetails.PT__c!=null)
            staffPT=String.valueof(accDetails.PT__c);
        system.debug('PT'+staffPT);
        if(accDetails.FT__c!=null)
            staffFT=String.valueof(accDetails.FT__c);
        insta=accDetails.Instagram__c;
        face=accDetails.Facebook__c;
        tweet=accDetails.twitter__c;
        
        affiliateContact  = accDetails.owner.name;
        affiliateEmail = accDetails.Affiliate_Email__c;
        affiliatePhone = accDetails.Affiliate_Phone__c;
        warehouseManager = accDetails.Warehouse_Manager__r.name;
        warehouseManagerEmail = accDetails.Warehouse_Manager_Email__c;
        warehouseManagerPhone = accDetails.Warehouse_Manager_Phone__c;
        
        panel1=false;
    }
    
    public pagereference showSec(){
        panel1=false;
        panel2=true;
        return null;
    }
    
    public Pagereference insertContact(){
        panel1=false;
        panel2=false;
        getcontc.AccountId=accId;
        if(!Test.isRunningTest()) {
            insert getcontc;
        }
        getcontc = new contact();
        getcont = new contact();
        setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
            [select id,name,phone,email,AccountId,Primary_contact__c,Executive_Contact__c,Status__c,Unsubscribe_Notifications__c,Executive_Home_Phone__c,
             (select id,username from users) from contact where AccountId IN:ids ]));
        setCon.setPageSize(size);  
        noOfRecords = setCon.getResultSize();
        getContacts();
        System.debug('idsss'+getcont);
        
        return null;
    }
    
    public PageReference editContact(){
        panel1=true;
        panel2=false;
        System.debug('Hi'+getcontc);
        System.debug('ConId'+conEdit);
        System.debug('ids-->'+ids);
        getcont = [select id,FirstName,lastname,phone,email,AccountId,Primary_contact__c,Executive_Contact__c,Status__c,Unsubscribe_Notifications__c,Executive_Home_Phone__c,
                   (select id,username from users) from contact where AccountId IN:ids and id=:conEdit];
        System.debug('Contlist'+getcont.FirstName);
        return null;
    }
    public pageReference updateContact(){
        try{
            panel1=false;
            panel2=false;
            update getcont;
            setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                [select id,name,phone,email,AccountId,Primary_contact__c,Executive_Contact__c,Status__c,Executive_Home_Phone__c,
                 Unsubscribe_Notifications__c,(select id,username from users) from contact where AccountId IN:ids ]));
            setCon.setPageSize(size);  
            noOfRecords = setCon.getResultSize();
            getContacts();
        }
        catch(Exception e)
        {
            Apexpages.addMessage(new Apexpages.message(ApexPages.Severity.Error,'Make another contact as Primary before removing this contact as Primary.'));
        } 
        return null;
    }
    public PageReference cancelContact(){
        panel1=false;
        panel2=false;
        return null;
    }
    public PageReference viewAllContacts(){
        panel1=false;
        panel2=false;
        panel3=true;
        setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
            [select id,name,phone,email,AccountId,Primary_contact__c,Executive_Contact__c,Status__c,Executive_Home_Phone__c,
             Unsubscribe_Notifications__c,(select id,username from users) from contact where AccountId IN:ids ]));
        getContacts();
        return null;
    }
    public PageReference goBack(){
        panel1=false;
        panel2=false; 
        panel3=false;                
        setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
            [select id,name,phone,email,AccountId,Primary_contact__c,Executive_Contact__c,Status__c,Executive_Home_Phone__c,
             Unsubscribe_Notifications__c,(select id,username from users) from contact where AccountId IN:ids ]));
        setCon.setPageSize(size);  
        noOfRecords = setCon.getResultSize();
        
        getContacts();
        return null;
    }
    Public Integer size{get;set;} 
    Public Integer noOfRecords{get; set;} 
    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {                
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [select id,name,phone,email,AccountId,Primary_contact__c,Executive_Contact__c,status__c,Executive_Home_Phone__c, Unsubscribe_Notifications__c,
                     (select id,username from users) from contact where AccountId IN:ids ]));
                setCon.setPageSize(size);  
                noOfRecords = setCon.getResultSize();
            }            
            return setCon;
        }
        set;
    }
    public List<Contact> getContacts(){
        return (List<Contact>) setCon.getRecords();
        
    }
    
    public PageReference editAccount(){
        hideAccount = true;
        showAccount = false;
        accDetails  = [Select id,Name,Phone,Billingaddress,BillingStreet,BillingCity,BillingState,BillingCountry,BillingPostalCode,website,annual_budget__c,
                        npo02__MembershipEndDate__c,npo02__MembershipJoinDate__c,ParentId,Agency_Impact__c,Agency_Mission__c ,PT__c,FT__c,
                       Instagram__c,Facebook__c,twitter__c,Membership_Status__c
                       from Account 
                       where id=:accId ];
        System.debug('##'+accDetails);
        name = accDetails.Name;
        Phone =accDetails.Phone;
        
        BillingStreet=accDetails.BillingStreet;
        BillingCity= accDetails.BillingCity;
        BillingState=accDetails.BillingState;
        BillingCountry= accDetails.BillingCountry;
        BillingPostalCode =accDetails.BillingPostalCode ;
        website=accDetails.website;
        annualbudget=accDetails.annual_budget__c;
        memberexpDate=String.valueOf(accDetails.npo02__MembershipEndDate__c);
        memberStatus=accDetails.Membership_Status__c;
        memberstartDate=String.valueof(accDetails.npo02__MembershipJoinDate__c);
        agencyImpact = accDetails.Agency_Impact__c;
        agencyMission=accDetails.Agency_Mission__c;
        if(accDetails.PT__c!=null)
            staffPT=String.valueof(accDetails.PT__c);
        system.debug('PT'+staffPT);
        if(accDetails.FT__c!=null)
            staffFT=String.valueof(accDetails.FT__c);
        insta=accDetails.Instagram__c;
        face=accDetails.Facebook__c;
        tweet=accDetails.twitter__c;
        ids.add(accDetails.id);
        //accLoc=accDetails.Parent.Community_URL_Prefix__c;
        return null;
    }
    
    public PageReference saveAccount(){
        hideAccount = false;
        showAccount = true;
        accDetails.Phone =Phone;
        accDetails.BillingStreet=BillingStreet;
        accDetails.BillingCity=BillingCity ;
        accDetails.BillingState= BillingState;
        accDetails.BillingCountry = BillingCountry;
        accDetails.BillingPostalCode = BillingPostalCode ;
        accDetails.website = website;
        accDetails.annual_budget__c = annualbudget;
        accDetails.Agency_Impact__c = agencyImpact;
        accDetails.Agency_Mission__c = agencyMission;
        if(String.isNotBlank(staffPT))
            accDetails.PT__c=Decimal.valueof(staffPT);
        else
            accDetails.PT__c=null;
        if(String.isNotBlank(staffFT))
            accDetails.FT__c=Decimal.valueof(staffFT);
        else
            accDetails.FT__c= null;
        accDetails.Instagram__c=insta;
        accDetails.Facebook__c=face;
        accDetails.twitter__c=tweet;
        system.debug('Before Updated'+accDetails);
       /* if(!Test.isRunningTest()) {
            update accDetails;
        }*/
        system.debug('Updated'+accDetails);
        return null;
    }
    public PageReference cancelAccount(){
        
        //accDetails = new Account();
        accDetails  = [Select id,Name,Phone,Billingaddress,BillingStreet,BillingCity,BillingState,BillingCountry,BillingPostalCode,website,annual_budget__c,
                        npo02__MembershipJoinDate__c,npo02__MembershipEndDate__c,Membership_Status__c,ParentId,Agency_Impact__c,Agency_Mission__c ,PT__c,FT__c,
                       Instagram__c,Facebook__c,twitter__c 
                       from Account 
                       where id=:accId ];
        Phone =accDetails.Phone;
        
        BillingStreet=accDetails.BillingStreet;
        BillingCity= accDetails.BillingCity;
        BillingState=accDetails.BillingState;
        BillingCountry= accDetails.BillingCountry;
        BillingPostalCode =accDetails.BillingPostalCode ;
        website=accDetails.website;
        annualbudget=accDetails.annual_budget__c;
        memberexpDate=String.valueOf(accDetails.npo02__MembershipEndDate__c);
        memberStatus=accDetails.Membership_Status__c;
        memberstartDate=String.valueof(accDetails.npo02__MembershipJoinDate__c);
        agencyImpact = accDetails.Agency_Impact__c;
        agencyMission=accDetails.Agency_Mission__c;
        staffPT=String.valueof(accDetails.PT__c);
        system.debug('PT'+staffPT);
        staffFT=String.valueof(accDetails.FT__c);
        insta=accDetails.Instagram__c;
        face=accDetails.Facebook__c;
        tweet=accDetails.twitter__c;
        hideAccount = false;
        showAccount = true;
        return null;
    }
    
}