force-app/main/default/objects/Account/fields/Annual_Budget__c.field-meta.xml
<CustomField>
    <fullName>Annual_Budget__c</fullName>
    <label>Annual Budget</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Annual_Budget</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account marked as Primary in this Contact&apos;s list of Organization Affiliations.</description>
    <inlineHelpText>The Account marked as Primary in this Contact&apos;s list of Organization Affiliations.</inlineHelpText>
    <label>Primary Affiliation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Do Not Use.  Use Organization Affiliations.</relationshipLabel>
    <relationshipName>PrimaryAffiliatedContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Number_Of_Projects__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Projects__c</fullName>
    <inlineHelpText>Number of individual activities serving the public good by using these ToolBank tools.</inlineHelpText>
    <label>Number Of Projects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Cleaning_R__c + Deposit_R__c + Total_Handling_Fees__c + Other_R__c + Total_Late_Fee__c+ Delivery_R_Fee__c + Membership_R_Fee__c+ Lost_R_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Annual_Budget.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>$0 - $100,000</fullName>
    </customValue>
    <customValue>
        <fullName>$100,001 - $250,000</fullName>
    </customValue>
    <customValue>
        <fullName>$250,001 - $500,000</fullName>
    </customValue>
    <customValue>
        <fullName>$500,001 - $750,000</fullName>
    </customValue>
    <customValue>
        <fullName>$750,001 - and above</fullName>
    </customValue>
    <customValue>
        <fullName>*Public School System</fullName>
    </customValue>
    <customValue>
        <fullName>*All Government Agencies</fullName>
    </customValue>
    <masterLabel>Annual Budget</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UpcomingOrderInfo_Ctrl.cls
public class UpcomingOrderInfo_Ctrl {
    
    public List<OrderItem> ol {get;set;}
    public List<order> ordr {get;set;}
    public string ordrId{get;set;}
    public account accDetails{set;get;}
    
    public List<Network> listOfNetwork {get; set;}
    public Domain dom {get;set;}
    public String finalURL {get;set;}
    public List<User> licen {get;set;}
    
    public upcomingOrderInfo_Ctrl() {
        Contact con = [Select contactId,contact.AccountId,contact.npsp__Primary_Affiliation__c from user where id=:userinfo.getuserid()].Contact;
        String accId;
        if(con.npsp__Primary_Affiliation__c != Null)
            accId = con.npsp__Primary_Affiliation__c;
        else accId = con.AccountId;
        System.debug(accId );
        accDetails  = [Select id,Name,Phone,Billingaddress,BillingStreet,BillingCity,BillingState,BillingCountry,BillingPostalCode,website,annual_budget__c,ParentId
                       from Account 
                       where id=:accId ];
        
        ordr =  [select id,Name,ordernumber,EffectiveDate,BillToContactId,TotalAmount,AccountId,Total_Amount__c,Number_Of_Projects__c  
                 from order where EffectiveDate >= Today and AccountId  = :accDetails.Id
                 limit 3];   
        
       /* listOfNetwork = new list<Network>();
        String urlpath ;
        listOfNetwork = [SELECT Name, UrlPathPrefix, Status FROM Network where Name = 'Agency Member' and status='live' limit 1];
        licen = [SELECT Profile.UserLicense.Name FROM User where id=:userinfo.getuserid()];
        List<Domain> domList= [select domain from domain];
        dom = domList[0]; //WHERE domain like '%NewAtlanta'];
        system.debug(domList);
        if(!listOfNetwork.isEmpty()) {
            for(Network n : listOfNetwork) {
                for(User l : licen) {
                    if(n.name.contains('Agency') && l.Profile.UserLicense.name == 'Customer Community'){
                        urlpath = n.UrlPathPrefix;
                        finalURL = 'https://'+dom.domain+'/'+urlpath;
                    }
                } 
            }
        }*/
        finalURL = label.CommunitySiteURL;
        System.debug('Final'+finalURL);
    }
    
    public Pagereference navigatePage() {
        PageReference pref; 
        System.debug(ordrId);
        try {
            pref = new PageReference(finalURL+'/s/detail/'+ordrId);
            pref.setredirect(true);
            
        } catch(exception e){
            system.debug(e);
        }
        return pref; 
    }
    public Pagereference viewAllPage(){
        PageReference pref;
        pref = new PageReference(finalURL+'/s/recordlist/Order/Recent');
        return pref; 
    }
}