force-app/main/default/objects/Account/fields/Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Date__c</fullName>
    <label>Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RK_AccountExpirationEmailAlertBatchTest.cls
@isTest
public class RK_AccountExpirationEmailAlertBatchTest {
    @testSetup static void setup() {
        Date setDate = Date.today()-335;
        Account acc = new Account(Name = 'Test Account', Approval_Date__c = setDate, Membership_Status__c = 'Active');
        insert acc;
        
        Contact con = new Contact(LastName = 'Test Contact', Email = 'test@test.com', Primary_Contact__c = true, AccountId = acc.Id);
        insert con;
    }
    @isTest static void testBatchClass() {
        Test.startTest();
        Database.executeBatch(new RK_AccountExpirationEmailAlertBatch());
        Test.stopTest();
    }
    @isTest static void testScheduleClass(){
        Test.startTest();
        String CRON_EXP = '0 0 1 * * ?';
        String jobId = System.schedule('JobName', CRON_EXP, new RK_AccountExpirationEmailAlertSch());
        Test.stopTest();
    }
}