force-app/main/default/objects/Account/fields/Membership_Fees_Amount__c.field-meta.xml
<CustomField>
    <fullName>Membership_Fees_Amount__c</fullName>
    <label>Membership Fees Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliate</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliate Orders</relationshipLabel>
    <relationshipName>AffiliateOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Ladders</fullName>
            </value>
            <value>
                <fullName>Moving</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Special Events</fullName>
            </value>
            <value>
                <fullName>Uncategorized</fullName>
            </value>
            <value>
                <fullName>Yardwork</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateRenwalOrderController.cls
public without sharing class CreateRenwalOrderController {
    
    Id accid; 

    public CreateRenwalOrderController(ApexPages.standardController sc){
        accid = sc.getId();
    }

    public pageReference createOrder(){

        Account acc = [SELECT Id,parentid,name,parent.Membership_Fees_Amount__c FROM Account WHERE Id=:accid];

        Order ord = new order();

        ord.Name = 'Membership Renewal-'+acc.name;
        ord.accountId = accid;
        ord.affiliate__c = acc.parentid;
        ord.pricebook2Id = label.pricebookId;
        ord.status = acc.parent.Membership_Fees_Amount__c!= Null && acc.parent.Membership_Fees_Amount__c != 0 ?'Unpaid ': 'Closed';
        ord.effectiveDate = Date.today();
        insert ord;

        Orderitem item = new Orderitem();

        item.orderId = ord.id;
        item.type__c = 'Additional Charges';
        item.Category__c = 'Membership';
        if(!Test.isRunningTest()){
        item.pricebookEntryId = label.MembershipFeePBEId;
        } else{
            item.pricebookEntryId = [SELECT Id FROM Pricebookentry limit 1].Id;
        }
        item.unitprice = acc.parent.Membership_Fees_Amount__c != NUll?acc.parent.Membership_Fees_Amount__c:0;
        item.quantity = 1;

        insert item;

        if(item.unitprice != Null && item.unitprice != 0){
            return new pageReference('/'+ord.Id).setRedirect(true);
        }else{
            return new pageReference('/'+accid).setRedirect(true);
        }

    }
}