force-app/main/default/objects/Credit__c/Credit__c.object-meta.xml
<CustomObject>
    <label>Credit</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Credit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CreditTriggerTest.cls
@isTest
public class CreditTriggerTest {
    
    @isTest
    private static void unitTest_1(){
        String recordTypeid  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Member Agency').getRecordTypeId();
        Account acc = TestDataFactory.createAccount('name',recordTypeid);
        Credit__c credit1 =  TestDataFactory.createCredit(acc.Id,Date.today());
        Credit__c credit2 = TestDataFactory.createCredit(acc.Id,Date.today().addDays(2));
        credit1.Amount__c = 105;
        credit2.isActive__c = false;
        update credit1;
    }

    @isTest
    private static void unitTest_2(){
        String recordTypeid  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Member Agency').getRecordTypeId();
        Account acc = TestDataFactory.createAccount('name',recordTypeid);
        Credit__c credit2 = TestDataFactory.createCredit(acc.Id,Date.today().addDays(2));
        credit2.isActive__c = false;
        update credit2;

        credit2.isActive__c = true;
        update credit2;

        delete credit2;
    }
}