force-app/main/default/objects/DebugLog__e/DebugLog__e.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <pluralLabel>Debug Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/DebugLog__e/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DebugLog__e/fields/LogLineNumber__c.field-meta.xml
<CustomField>
    <fullName>LogLineNumber__c</fullName>
    <label>Log Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DebugLog__e/fields/LogMessage__c.field-meta.xml
<CustomField>
    <fullName>LogMessage__c</fullName>
    <label>Log Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DebugLog__e/fields/RunningUser__c.field-meta.xml
<CustomField>
    <fullName>RunningUser__c</fullName>
    <label>Running User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderLog__c/OrderLog__c.object-meta.xml
<CustomObject>
    <label>Order Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Order Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderLog__c/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderLog__c/fields/ApexMethod__c.field-meta.xml
<CustomField>
    <fullName>ApexMethod__c</fullName>
    <label>Apex Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderLog__c/fields/LogLineNumber__c.field-meta.xml
<CustomField>
    <fullName>LogLineNumber__c</fullName>
    <label>Log Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderLog__c/fields/LogMessage__c.field-meta.xml
<CustomField>
    <fullName>LogMessage__c</fullName>
    <label>Log Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/OrderLog__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>Record Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderLog__c/fields/RunningUser__c.field-meta.xml
<CustomField>
    <fullName>RunningUser__c</fullName>
    <label>Running User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DebugLogtriggerHandler.cls
public class DebugLogtriggerHandler {
    
    public static void afterInsert(List<DebugLog__e> debugLogs){
        List<OrderLog__c> orderLogs = new List<OrderLog__c>();
        for(DebugLog__e logevt :debugLogs) {
            OrderLog__c odLog = new OrderLog__c();
            odLog = formOrderLog(odLog, logevt);
            orderLogs.add(odLog);
        }
        if (!Schema.sObjectType.OrderLog__c.isCreateable()) {
            return;
        }
        if(!orderLogs.isEmpty()){
            insert orderLogs;
        }
    }
    
    public static OrderLog__c formOrderLog(OrderLog__c odLog, DebugLog__e logevt){
        
        odLog.ApexClass__c = logevt.ApexClass__c;
        odLog.ApexMethod__c = logevt.ApexMethod__c;
        odLog.LogLineNumber__c = logevt.LogLineNumber__c;
        odLog.RecordId__c = logevt.RecordId__c;
        odLog.RunningUser__c = logevt.RunningUser__c;
        odLog.LogMessage__c = logevt.LogMessage__c;
        odLog.StackTrace__c = logevt.StackTrace__c;
        
        return odLog;
    }
}