force-app/main/default/objects/DebugLog__e/DebugLog__e.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <pluralLabel>Debug Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/DebugLog__e/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DebugLog__e/fields/LogLineNumber__c.field-meta.xml
<CustomField>
    <fullName>LogLineNumber__c</fullName>
    <label>Log Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DebugLog__e/fields/LogMessage__c.field-meta.xml
<CustomField>
    <fullName>LogMessage__c</fullName>
    <label>Log Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DebugLog__e/fields/RunningUser__c.field-meta.xml
<CustomField>
    <fullName>RunningUser__c</fullName>
    <label>Running User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DebugLogUtil.cls
public with sharing class DebugLogUtil {

    // Define the Platform Event
    private final DebugLog__e logEvent;
    
    // Constructor
    public DebugLogUtil() {
        logEvent = new DebugLog__e();
    }
    public void publishDebugLog(String log, String className, String methodName, String lineNumber, String relatedRecordId, Id userId) {
        logEvent.ApexClass__c = className;
        logEvent.ApexMethod__c = methodName;
        logEvent.LogMessage__c = log;
        logEvent.LogLineNumber__c = lineNumber;
        logEvent.RecordId__c = relatedRecordId;
        logEvent.RunningUser__c = userId;

        EventBus.publish(logEvent);
    }
    
    public void publishExceptionLog(Exception ex, String className, String methodName, String lineNumber, String relatedRecordId, Id userId) {
        logEvent.ApexClass__c = className;
        logEvent.ApexMethod__c = methodName;
        logEvent.LogLineNumber__c = lineNumber;
        logEvent.RecordId__c = relatedRecordId;
        logEvent.RunningUser__c = userId;
        logEvent.LogMessage__c = ex?.getMessage();
        logEvent.StackTrace__c = ex?.getStackTraceString();

        EventBus.publish(logEvent);
    }
}