force-app/main/default/objects/Api_Credentials__mdt/Api_Credentials__mdt.object-meta.xml
<CustomObject>
    <label>Api Credential</label>
    <pluralLabel>Api Credential</pluralLabel>
</CustomObject>

force-app/main/default/objects/Api_Credentials__mdt/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client Id (key)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Api_Credentials__mdt/fields/Clinet_Secret__c.field-meta.xml
<CustomField>
    <fullName>Clinet_Secret__c</fullName>
    <label>Clinet Secret</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Api_Credentials__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Api_Credentials__mdt/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Api_Credentials__mdt/fields/version__c.field-meta.xml
<CustomField>
    <fullName>version__c</fullName>
    <label>version</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/On_Shelf_Quantity_F__c.field-meta.xml
<CustomField>
    <fullName>On_Shelf_Quantity_F__c</fullName>
    <formula>Current_Inventory_F__c - Out_F__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>These tools are currently in the warehouse but may be reserved for other orders.</inlineHelpText>
    <label>On Shelf Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>Txn-{00000000}</displayFormat>
        <label>Transaction No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Donating_Company__c.field-meta.xml
<CustomField>
    <fullName>Donating_Company__c</fullName>
    <label>Donating Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Worn - Out</fullName>
            </value>
            <value>
                <fullName>No Longer Carry</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Gift Card</fullName>
            </value>
            <value>
                <fullName>Restricted Funds</fullName>
            </value>
            <value>
                <fullName>General Funds</fullName>
            </value>
            <value>
                <fullName>Corporate Donation</fullName>
            </value>
            <value>
                <fullName>Individual Donation</fullName>
            </value>
            <value>
                <fullName>Member Agency Donation</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Rebranding</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Destroyed</fullName>
            </value>
            <value>
                <fullName>Increase</fullName>
            </value>
            <value>
                <fullName>Decrease</fullName>
            </value>
            <value>
                <fullName>Lost - Return</fullName>
            </value>
            <value>
                <fullName>Lost from Inventory</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
                <isActive>false</isActive>
                <label>Allocated</label>
            </value>
            <value>
                <fullName>Donated</fullName>
                <isActive>false</isActive>
                <label>Donated</label>
            </value>
            <value>
                <fullName>Donation</fullName>
                <isActive>false</isActive>
                <label>Donation</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Purchased</fullName>
                <isActive>false</isActive>
                <label>Purchased</label>
            </value>
            <value>
                <fullName>Return</fullName>
                <isActive>false</isActive>
                <label>Return</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transfer_From__c.field-meta.xml
<CustomField>
    <fullName>Transfer_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transfer From</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transfered Transactions(Out)</relationshipLabel>
    <relationshipName>TransferedTransactionsOut</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transfer_To__c.field-meta.xml
<CustomField>
    <fullName>Transfer_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transfer To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Incoming Transactions (In)</relationshipLabel>
    <relationshipName>IncomingTransactionsIn</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/Fulfilled.recordType-meta.xml
<RecordType>
    <fullName>Fulfilled</fullName>
    <active>true</active>
    <label>Fulfilled</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Lost.recordType-meta.xml
<RecordType>
    <fullName>Lost</fullName>
    <active>true</active>
    <label>Lost</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Out_Of_Service.recordType-meta.xml
<RecordType>
    <fullName>Out_Of_Service</fullName>
    <active>true</active>
    <label>Out Of Service</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Retired.recordType-meta.xml
<RecordType>
    <fullName>Retired</fullName>
    <active>true</active>
    <label>Retired</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Returned.recordType-meta.xml
<RecordType>
    <fullName>Returned</fullName>
    <active>true</active>
    <label>Returned</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/Transfer.recordType-meta.xml
<RecordType>
    <fullName>Transfer</fullName>
    <active>true</active>
    <label>Transfer</label>
</RecordType>

force-app/main/default/classes/CreateTransaction.cls
public without sharing class CreateTransaction {
    

    @AuraEnabled(cacheable = true)
    public static List<PickListOption> getRecordType(){
        Schema.DescribeSObjectResult d = Schema.SObjectType.Transaction__c; 
        Map<Id,Schema.RecordTypeInfo> rtMapById = d.getRecordTypeInfosById();

        List<PickListOption> recordTypeOptionList = new list<PickListOption>();
        for(Schema.RecordTypeInfo recInfo: rtMapById.values()){

            if(recInfo.isActive() && recInfo.getName() != 'Master' && recInfo.getName() != 'Fulfilled' && recInfo.getName() != 'Returned'){
                PickListOption rectype = new PickListOption();
                rectype.label = recInfo.getName();
                rectype.value = recInfo.getRecordTypeId();
                System.debug(recInfo);
                recordTypeOptionList.add(rectype);
            }
        }

        return recordTypeOptionList;
    }

    @AuraEnabled
    public static String createTransaction(String inventoryId, String recordTypeId, String subType, Integer qty, String note, String affiliateId){
        String recordTypeName = [Select Id, Name, DeveloperName FROM RecordType WHERE Id = :recordTypeId LIMIT 1].DeveloperName;
        Asset inv1 = [SELECT id, accountId,On_Shelf_Quantity_F__c,product2Id FROM Asset WHERE Id =: inventoryId];
        if(qty > 0) {
            if(recordTypeName == 'Out_Of_Service' || recordTypeName == 'Transfer' || subType == 'Decrease' || subType == 'Lost from Inventory' || recordTypeName == 'Retired') {
                if(qty <= inv1.On_Shelf_Quantity_F__c) {
                    if(recordTypeName == 'Transfer') {
                        Asset inv = [SELECT Id FROM Asset WHERE AccountId =: affiliateId AND product2Id =:inv1.product2Id];
                        Transaction__c trans = new Transaction__c();
                        trans.sub_type__c = 'Decrease';
                        trans.inventory__c = inventoryId;
                        trans.Transfer_From__c = inv1.accountId;
                        trans.Transfer_To__c = affiliateId;
                        trans.recordTypeId = recordTypeId;
                        trans.quantity__c = qty;
                        trans.note__c = note;
                        Transaction__c trans2 = new Transaction__c();
                        trans2.sub_type__c = 'Increase';
                        trans2.inventory__c = inv.Id;
                        trans2.Transfer_From__c = inv1.accountId;
                        trans2.Transfer_To__c = affiliateId;
                        trans2.recordTypeId = recordTypeId;
                        trans2.quantity__c = qty;
                        trans2.note__c = note;
                        insert new list<Transaction__c>{trans,trans2};
                            } else {
                                Transaction__c trans = new Transaction__c();
                                trans.sub_type__c = subType;
                                trans.inventory__c = inventoryId;
                                trans.recordTypeId = recordTypeId;
                                trans.quantity__c = qty;
                                trans.note__c = note;
                                insert trans;
                            }
                } else {
                    return 'The Quantity entered exceeds the On Shelf Quantity for this tool';
                }
            } else {
                Transaction__c trans = new Transaction__c();
                trans.sub_type__c = subType;
                trans.inventory__c = inventoryId;
                trans.recordTypeId = recordTypeId;
                trans.quantity__c = qty;
                trans.note__c = note;
                insert trans;
            }
        } else {
            return 'The Quantity entered must be greater than 0';
        }
        return 'Successfull';
    }

    @AuraEnabled
    public static List<PickListOption> getValues(String objectType, String recordTypeId, String fieldName) {
        
        // Create the endpoint dynamically for your og
        Api_Credentials__mdt api = Api_Credentials__mdt.getInstance('Salesforce');
        String endpoint = api.endpoint__c+'/services';   
        
        String tokenEndpoint = endpoint+'/oauth2/token?';
        tokenEndpoint += 'grant_type=password&client_id='+api.client_id__c
                        +'&client_secret='+api.Clinet_Secret__c
                        +'&username='+api.username__c
                        +'&password='+api.password__c;
        HttpRequest tokenReq = new HttpRequest();
        tokenReq.setEndpoint(tokenEndpoint);
        tokenReq.setMethod('POST');
        Http tokenHttp = new Http();

        HTTPResponse tokenRes =tokenHttp.send(tokenReq);
        Map<String, object> token = (Map<String, object>)JSON.deserializeUntyped(tokenRes.getBody());
        String access_token = (String)token.get('access_token');

        endpoint += '/data/'+api.version__c;
        endpoint += '/ui-api/object-info/' + objectType + '/picklist-values/' + recordTypeId + '/' + fieldName;
        
        
        EncodingUtil.urlEncode(endpoint,'UTF-8');
        
        // Call the API in order to get the values 
        HttpRequest req = new HttpRequest();
        
        // Since, we can not use the UserInfo.getSessionId() method here, I am using a Visualforce page in order
        // to extract the session id which we can use for making API calls
        
        req.setHeader('Authorization', 'Bearer ' + access_token);//'00D020000008pmO!AREAQC2xvIy.8Fj3ZSuilgG9Gi48WrFqvOlut5hXEyI0wegmSyZpZYSSBrSBMPt9WhVZKMm3vXSlXVTNNWDFe3dIobocO5ZZ');
        req.setHeader('Accept', 'application/json '); 
        req.setHeader('Content-Type', 'application/json');
        req.setEndpoint(endpoint);
        req.setMethod('GET');
        Http http = new Http();
        
        HTTPResponse res = http.send(req);
        Map<String, String> result = new Map<String,String>();
        Map<String, List<String>> mapControllingWithDependentList = new Map<String,List<String>>();
        Map<Object, String> mapControllingValueWithIndex = new Map<Object,String>();
        Map<String, List<String>> mapPicklistValues = new Map<String,List<String>>();
        
        List<PickListOption> subtypeList = new List<PickListOption>();
        if( res.getStatus() == 'OK' && res.getStatusCode() == 200 ) {
            
            Map<String,Object> root = (Map<String,Object>) JSON.deserializeUntyped( res.getBody() );
            
            System.debug( ' Response Body : ' + root.get('values'));
            for(Object obj: (List<Object>)root.get('values'))   {
                PickListOption sub = new PickListOption();
                Map<String,object> temp = (Map<String,object>)obj;
                sub.label = (String)temp.get('label');
                sub.value = (String)temp.get('value');
                if(sub.value != 'Lost - Return') {
                    subtypeList.add(sub);
                }
            }
        }
        return subtypeList;
        
    }

    @AuraEnabled
    public static String createBulkTransaction(String toolList, String recordTypeId, String subType, String affiliateId){
        System.debug('toolList :: '+toolList);
        List<Object> invItemList = (List<Object>) json.deserializeUntyped(toolList);
        String recordTypeName = [Select Id, Name, DeveloperName FROM RecordType WHERE Id = :recordTypeId LIMIT 1].DeveloperName;
        
        List<String> productIdList = new List<String>();
        Map<String,Asset> productIdToAssetMap = new Map<String, Asset>();
        for(Object obj: invItemList){
            System.debug(obj);
            Map<String, Object> tool = (Map<String, Object>)obj;
            productIdList.add((String)tool.get('Product2Id'));
        }
        for(Asset asset: [SELECT Id, Product2Id FROM Asset WHERE AccountId =: affiliateId AND product2Id IN: productIdList]){
            productIdToAssetMap.put(asset.product2Id,asset);
        }

        list<Transaction__c> transactionToInsert = new List<Transaction__c>();
        for(Object obj: invItemList){
            Map<String, Object> tool = (Map<String, Object>)obj;
            if(recordTypeName == 'Transfer') {
                
                Transaction__c trans = new Transaction__c();
                trans.sub_type__c = 'Decrease';
                trans.inventory__c = (String)tool.get('InventoryId');
                trans.recordTypeId = recordTypeId;
                trans.quantity__c = Decimal.valueOf((String)tool.get('Quantity'));
                trans.note__c = (String)tool.get('Note');
                Transaction__c trans2 = new Transaction__c();
                trans2.sub_type__c = 'Increase';
                trans2.inventory__c = productIdToAssetMap.get((String)tool.get('Product2Id')).Id;
                trans2.recordTypeId = recordTypeId;
                trans2.quantity__c = Decimal.valueOf((String)tool.get('Quantity'));
                trans2.note__c = (String)tool.get('Note');
                transactionToInsert.add(trans);
                transactionToInsert.add(trans2);
            } else {
                    Transaction__c trans = new Transaction__c();
                    trans.sub_type__c = subType;
                    trans.inventory__c = (String)tool.get('InventoryId');
                    trans.recordTypeId = recordTypeId;
                    trans.quantity__c = Decimal.valueOf((String)tool.get('Quantity'));
                    trans.note__c = (String)tool.get('Note');
                    trans.donating_company__c = (String)tool.get('DonationCompany');
                    transactionToInsert.add(trans);
                }
        }

        if(transactionToInsert.size() >0){
            insert transactionToInsert;
        }

        return 'Success';
    }

    public class PickListOption{
        @AuraEnabled
        public String value;
        @AuraEnabled
        public string label;
    }
}